Repository date-fns/date-fns, pull requests merged in 2018-06, with the labels that each got.

#789 Add `getTimezoneOffsetInMilliseconds` utility function
  CHANGELOG.md
  src/_lib/addUTCMinutes/index.js
  src/_lib/addUTCMinutes/test.js
  src/_lib/getTimezoneOffsetInMilliseconds/index.js
  src/_lib/getTimezoneOffsetInMilliseconds/test.js
  src/differenceInCalendarDays/index.js
  src/differenceInCalendarISOWeeks/index.js
  src/differenceInCalendarWeeks/index.js
  src/format/index.js
  src/formatDistance/index.js
  src/formatDistanceStrict/index.js
  src/formatRelative/index.js
  src/parse/index.js
  src/toDate/index.js
Labels: 🐛 Bug

#788 [V2] Add TH locale
  src/locale/th/_lib/formatLong/index.js
  src/locale/th/_lib/formatRelative/index.js
  src/locale/th/_lib/localize/index.js
  src/locale/th/_lib/match/index.js
  src/locale/th/index.js
  src/locale/th/test.js
Labels: ⛴ Ship it!, 🌏 I18n

#796 add eachWeekOfInterval
  CHANGELOG.md
  src/eachWeekOfInterval/benchmark.js
  src/eachWeekOfInterval/index.d.ts
  src/eachWeekOfInterval/index.js
  src/eachWeekOfInterval/index.js.flow
  src/eachWeekOfInterval/test.js
  src/esm/fp/index.js
  src/esm/index.js
  src/fp/eachWeekOfInterval/index.d.ts
  src/fp/eachWeekOfInterval/index.js
  src/fp/eachWeekOfInterval/index.js.flow
  src/fp/eachWeekOfIntervalWithOptions/index.d.ts
  src/fp/eachWeekOfIntervalWithOptions/index.js
  src/fp/eachWeekOfIntervalWithOptions/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/test.js
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!
