Repository date-fns/date-fns, pull requests merged in 2018-09, with the labels that each got.

#867 Update HE locale to support v2
  docs/i18n.md
  outdatedLocales.json
  src/esm/locale/index.js
  src/locale/he/_lib/formatDistance/index.js
  src/locale/he/_lib/formatDistance/test.js
  src/locale/he/_lib/formatLong/index.js
  src/locale/he/_lib/formatRelative/index.js
  src/locale/he/_lib/localize/index.js
  src/locale/he/_lib/match/index.js
  src/locale/he/index.js
  src/locale/he/test.js
  src/locale/index.js
Labels: 🌏 I18n

#855 Updated it locale for version 2.0
  outdatedLocales.json
  src/locale/it/_lib/formatLong/index.js
  src/locale/it/_lib/formatRelative/index.js
  src/locale/it/_lib/localize/index.js
  src/locale/it/_lib/match/index.js
  src/locale/it/index.js
  src/locale/it/test.js
Labels: 🌏 I18n

#864 add basic support for hu and lt localizations
  src/esm/locale/index.js
  src/locale/hu/_lib/formatDistance/index.js
  src/locale/hu/_lib/formatDistance/test.js
  src/locale/hu/_lib/formatLong/index.js
  src/locale/hu/_lib/formatRelative/index.js
  src/locale/hu/_lib/localize/index.js
  src/locale/hu/_lib/match/index.js
  src/locale/hu/index.d.ts
  src/locale/hu/index.js
  src/locale/hu/index.js.flow
  src/locale/hu/test.js
  src/locale/index.js
  src/locale/index.js.flow
  src/locale/lt/_lib/formatDistance/index.js
  src/locale/lt/_lib/formatDistance/test.js
  src/locale/lt/_lib/formatLong/index.js
  src/locale/lt/_lib/formatRelative/index.js
  src/locale/lt/_lib/localize/index.js
  src/locale/lt/_lib/match/index.js
  src/locale/lt/index.d.ts
  src/locale/lt/index.js
  src/locale/lt/index.js.flow
  src/locale/lt/test.js
  typings.d.ts
Labels: 🌏 I18n

#846 Update VI locale for v2
  outdatedLocales.json
  src/locale/vi/_lib/formatDistance/index.js
  src/locale/vi/_lib/formatDistance/test.js
  src/locale/vi/_lib/formatLong/index.js
  src/locale/vi/_lib/formatRelative/index.js
  src/locale/vi/_lib/localize/index.js
  src/locale/vi/_lib/match/index.js
  src/locale/vi/index.js
  src/locale/vi/test.js
Labels: 🌏 I18n

#775 Add FI locale
  src/locale/fi/_lib/formatLong/index.js
  src/locale/fi/_lib/formatRelative/index.js
  src/locale/fi/_lib/localize/index.js
  src/locale/fi/_lib/match/index.js
  src/locale/fi/index.js
  src/locale/fi/test.js
Labels: 🌏 I18n

#859 Added locale Galician (gl).
  docs/i18n.md
  src/locale/gl/_lib/formatDistance/index.js
  src/locale/gl/_lib/formatDistance/test.js
  src/locale/gl/_lib/formatLong/index.js
  src/locale/gl/_lib/formatRelative/index.js
  src/locale/gl/_lib/localize/index.js
  src/locale/gl/_lib/match/index.js
  src/locale/gl/index.d.ts
  src/locale/gl/index.js
  src/locale/gl/index.js.flow
  src/locale/gl/test.js
Labels: 🌏 I18n

#886 Disable the problematic Galician locale
  CHANGELOG.md
  flow-typed/mocha.js.flow
  outdatedLocales.json
  src/esm/locale/index.js
  src/locale/gl/_lib/formatDistance/test.js
  src/locale/gl/test.js
  src/locale/index.js
Labels: 🌏 I18n

#870 add support for getUnixTime
  src/esm/fp/index.js
  src/esm/index.js
  src/fp/getUnixTime/index.d.ts
  src/fp/getUnixTime/index.js
  src/fp/getUnixTime/index.js.flow
  src/fp/getUnixTimeWithOptions/index.d.ts
  src/fp/getUnixTimeWithOptions/index.js
  src/fp/getUnixTimeWithOptions/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/getUnixTime/benchmark.js
  src/getUnixTime/index.d.ts
  src/getUnixTime/index.js
  src/getUnixTime/index.js.flow
  src/getUnixTime/test.js
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: 🎉 Feature

#839 decade related helpers
  src/endOfDecade/benchmark.js
  src/endOfDecade/index.d.ts
  src/endOfDecade/index.js
  src/endOfDecade/index.js.flow
  src/endOfDecade/test.js
  src/esm/fp/index.js
  src/esm/index.js
  src/fp/endOfDecade/index.d.ts
  src/fp/endOfDecade/index.js
  src/fp/endOfDecade/index.js.flow
  src/fp/endOfDecadeWithOptions/index.d.ts
  src/fp/endOfDecadeWithOptions/index.js
  src/fp/endOfDecadeWithOptions/index.js.flow
  src/fp/getDecade/index.d.ts
  src/fp/getDecade/index.js
  src/fp/getDecade/index.js.flow
  src/fp/getDecadeWithOptions/index.d.ts
  src/fp/getDecadeWithOptions/index.js
  src/fp/getDecadeWithOptions/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/lastDayOfDecade/index.d.ts
  src/fp/lastDayOfDecade/index.js
  src/fp/lastDayOfDecade/index.js.flow
  src/fp/lastDayOfDecadeWithOptions/index.d.ts
  src/fp/lastDayOfDecadeWithOptions/index.js
  src/fp/lastDayOfDecadeWithOptions/index.js.flow
  src/fp/startOfDecade/index.d.ts
  src/fp/startOfDecade/index.js
  src/fp/startOfDecade/index.js.flow
  src/fp/startOfDecadeWithOptions/index.d.ts
  src/fp/startOfDecadeWithOptions/index.js
  src/fp/startOfDecadeWithOptions/index.js.flow
  src/getDecade/benchmark.js
  src/getDecade/index.d.ts
  src/getDecade/index.js
  src/getDecade/index.js.flow
  src/getDecade/test.js
  src/index.js
  src/index.js.flow
  src/lastDayOfDecade/benchmark.js
  src/lastDayOfDecade/index.d.ts
  src/lastDayOfDecade/index.js
  src/lastDayOfDecade/index.js.flow
  src/lastDayOfDecade/test.js
  src/startOfDecade/benchmark.js
  src/startOfDecade/index.d.ts
  src/startOfDecade/index.js
  src/startOfDecade/index.js.flow
  src/startOfDecade/test.js
  typings.d.ts
Labels: 🎉 Feature

#892 Add information on excluding languages using Webpack Context Replacement Plugin
  docs/index.js
  docs/webpack.md
Labels: 📃 Docs

#837 Add docs.json to gitignore
  .gitignore
Labels: ⚙️ Chore
