Repository date-fns/date-fns, pull requests merged in 2018-12, with the labels that each got.

#1002 Fix HU language
  src/locale/hu/_lib/formatDistance/index.js
  src/locale/hu/_lib/formatDistance/test.js
  src/locale/hu/index.js
  src/locale/hu/test.js
Labels: 🌏 I18n

#996 Revisit Swedish locale
  src/locale/sv/_lib/formatRelative/index.js
  src/locale/sv/test.js
Labels: 🌏 I18n

#1003 Fix DST issue (closes #972, closes #992)
  scripts/test/dst.sh
  scripts/test/travis.sh
  src/toDate/index.js
  test/dst/toDate/basic.js
  test/dst/toDate/samoa.js
Labels: 🐛 Bug

#1005 Backport DST fix from v2
  CHANGELOG.md
  src/_lib/getTimezoneOffsetInMilliseconds/index.js
  src/parse/index.js
Labels: 🐛 Bug, 👴 v1

#717 Add SR locale
  src/locale/sr/build_distance_in_words_locale/index.js
  src/locale/sr/build_distance_in_words_locale/test.js
  src/locale/sr/build_format_locale/index.js
  src/locale/sr/build_format_locale/test.js
  src/locale/sr/index.d.ts
  src/locale/sr/index.js
  src/locale/sr/test.js
Labels: 🌏 I18n, 👴 v1

#913 V1: Fix monthsFull misspelling in TH locale.
  src/locale/th/build_format_locale/index.js
  src/locale/th/build_format_locale/test.js
Labels: 🌏 I18n, 👴 v1

#716 Add BE locale
  src/locale/be/build_distance_in_words_locale/index.js
  src/locale/be/build_distance_in_words_locale/test.js
  src/locale/be/build_format_locale/index.js
  src/locale/be/build_format_locale/test.js
  src/locale/be/index.d.ts
  src/locale/be/index.js
  src/locale/be/test.js
Labels: 🌏 I18n, 👴 v1

#880 Improve ja translation of distanceInWords
  src/locale/ja/build_distance_in_words_locale/index.js
  src/locale/ja/build_distance_in_words_locale/test.js
Labels: 🌏 I18n, 👴 v1

#994 Add docs outlining time zone support via 3rd party libraries
  docs/index.js
  docs/timeZones.md
Labels: 🌐 TZ, 📃 Docs

#1011 Update i18n.md
  docs/i18n.md
Labels: 📃 Docs

#1013 change date pattern to meet the nation standard (GB/T 7408-2005)
  src/locale/zh-CN/_lib/formatLong/index.js
  src/locale/zh-CN/_lib/localize/index.js
  src/locale/zh-CN/_lib/match/index.js
  src/locale/zh-CN/test.js
Labels: 🌏 I18n

#1019 Milliseconds aren't detected after seconds/Unix timestamp (closes #985)
  src/_lib/assign/index.js
  src/_lib/assign/test.js
  src/_lib/cloneObject/index.js
  src/parse/_lib/parsers/index.js
  src/parse/index.js
  src/parse/test.js
Labels: 🌏 I18n, 🐛 Bug
