Repository date-fns/date-fns, pull requests merged in 2018-10, with the labels that each got.

#897 improve ja translation of format distance
  src/locale/ja/_lib/formatDistance/index.js
  src/locale/ja/_lib/formatDistance/test.js
Labels: 🌏 I18n

#900 🎉9️⃣0️⃣0️⃣🎂 Use getISOHours in Spanish locale (closes #884)
  src/locale/es/_lib/formatRelative/index.js
Labels: 🐛 Bug

#910 Rework ESM to fully support tree-shaking
  CHANGELOG.md
  docs/esm.md
  docs/fp.md
  docs/gettingStarted.md
  docs/i18n.md
  examples/typescript/example.ts
  examples/typescript/fp.ts
  examples/typescript/misc.ts
  examples/typescript/package.json
  examples/typescript/yarn.lock
  examples/webpack-4.x/example.js
  examples/webpack-4.x/fp.js
  examples/webpack-4.x/minimal.js
  examples/webpack-4.x/misc.js
  examples/webpack-4.x/package.json
  examples/webpack-4.x/yarn.lock
  package.json
  scripts/_lib/listFPFns.js
  scripts/_lib/listFns.js
  scripts/_lib/listLocales.js
  scripts/build/package.sh
  scripts/build/packages.js
  scripts/build/templates/subModulePackage.json
  scripts/build/templates/subSubModulePackage.json
  scripts/build/templates/subSubSubModulePackage.json
  yarn.lock
Labels: 🎉 Feature

#934 Fix usage of const causing UglifyJS fail on date-fns
  src/_lib/protectedTokens/index.js
Labels: 🐛 Bug

#926 Update Greek locale
  outdatedLocales.json
  src/locale/el/_lib/formatDistance/index.js
  src/locale/el/_lib/formatDistance/test.js
  src/locale/el/_lib/formatLong/index.js
  src/locale/el/_lib/formatRelative/index.js
  src/locale/el/_lib/formatters/index.js
  src/locale/el/_lib/localize/index.js
  src/locale/el/_lib/match/index.js
  src/locale/el/index.js
  src/locale/el/test.js
Labels: 🌏 I18n

#928 add new function roundToNearestMinutes
  CHANGELOG.md
  src/esm/fp/index.js
  src/esm/index.js
  src/esm/locale/index.js
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/roundToNearestMinutes/index.d.ts
  src/fp/roundToNearestMinutes/index.js
  src/fp/roundToNearestMinutes/index.js.flow
  src/fp/roundToNearestMinutesWithOptions/index.d.ts
  src/fp/roundToNearestMinutesWithOptions/index.js
  src/fp/roundToNearestMinutesWithOptions/index.js.flow
  src/fp/test.js
  src/index.js
  src/index.js.flow
  src/locale/index.js
  src/roundToNearestMinutes/index.d.ts
  src/roundToNearestMinutes/index.js
  src/roundToNearestMinutes/index.js.flow
  src/roundToNearestMinutes/test.js
  typings.d.ts
Labels: 🎉 Feature

#943 Adding Arabic (Saudi Arabia) locale
  src/locale/ar-SA/_lib/formatDistance/index.js
  src/locale/ar-SA/_lib/formatDistance/test.js
  src/locale/ar-SA/_lib/formatLong/index.js
  src/locale/ar-SA/_lib/formatRelative/index.js
  src/locale/ar-SA/_lib/localize/index.js
  src/locale/ar-SA/_lib/match/index.js
  src/locale/ar-SA/index.d.ts
  src/locale/ar-SA/index.js
  src/locale/ar-SA/index.js.flow
  src/locale/ar-SA/test.js
Labels: 🌏 I18n

#938 Fix error in documentation (example) of getUnixTime
  src/esm/locale/index.js
  src/getUnixTime/index.js
  src/locale/index.js
Labels: 📃 Docs

#948 Various fixes for ar-SA locale
  src/esm/locale/index.js
  src/locale/ar-SA/_lib/formatDistance/test.js
  src/locale/ar-SA/_lib/localize/index.js
  src/locale/ar-SA/_lib/match/index.js
  src/locale/ar-SA/index.d.ts
  src/locale/ar-SA/test.js
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: 🌏 I18n

#879 Added three new week helper functions: getWeekendsBetween, getWeekend…
  CHANGELOG.md
  src/eachWeekendOfInterval/benchmark.js
  src/eachWeekendOfInterval/index.d.ts
  src/eachWeekendOfInterval/index.js
  src/eachWeekendOfInterval/index.js.flow
  src/eachWeekendOfInterval/test.js
  src/eachWeekendOfMonth/benchmark.js
  src/eachWeekendOfMonth/index.d.ts
  src/eachWeekendOfMonth/index.js
  src/eachWeekendOfMonth/index.js.flow
  src/eachWeekendOfMonth/test.js
  src/eachWeekendOfYear/benchmark.js
  src/eachWeekendOfYear/index.d.ts
  src/eachWeekendOfYear/index.js
  src/eachWeekendOfYear/index.js.flow
  src/eachWeekendOfYear/test.js
  src/getWeekendsBetween/benchmark.js
  src/getWeekendsBetween/index.d.ts
  src/getWeekendsBetween/index.js
  src/getWeekendsBetween/index.js.flow
  src/getWeekendsBetween/test.js
Labels: 🎉 Feature

#962 Add mini changelog to misc functions (see #957)
  CHANGELOG.md
  src/closestIndexTo/index.js
  src/closestTo/index.js
  src/format/index.js
  src/formatDistance/index.js
  src/formatDistanceStrict/index.js
  src/isValid/index.js
  src/max/index.js
  src/min/index.js
  src/parse/index.js
  src/toDate/index.js
Labels: 📃 Docs

#961 Add mini changelog to interval functions (see #957)
  CHANGELOG.md
  src/areIntervalsOverlapping/index.js
  src/eachDayOfInterval/index.js
  src/getOverlappingDaysInIntervals/index.js
  src/isWithinInterval/index.js
Labels: 📃 Docs

#960 Add mini changelog to ISO week functions (see #957)
  CHANGELOG.md
  src/addISOWeekYears/index.js
  src/differenceInCalendarISOWeekYears/index.js
  src/differenceInISOWeekYears/index.js
  src/endOfISOWeekYear/index.js
  src/getISOWeekYear/index.js
  src/isSameISOWeekYear/index.js
  src/lastDayOfISOWeekYear/index.js
  src/setISOWeekYear/index.js
  src/subISOWeekYears/index.js
Labels: 📃 Docs
