Repository date-fns/date-fns, pull requests merged in 2018-04, with the labels that each got.

#596 Fix fr locales and enable tests in fr locale
  src/locale/fr-CH/_lib/formatLong/index.js
  src/locale/fr-CH/_lib/match/index.js
  src/locale/fr/_lib/formatLong/index.js
  src/locale/fr/_lib/formatRelative/index.js
  src/locale/fr/_lib/localize/index.js
  src/locale/fr/_lib/match/index.js
Labels: I18n, ⛴ Ship it!

#657 Change norwegian date formats to correct ones.
  src/locale/nb/_lib/formatLong/index.js
Labels: I18n

#705 Fix Dutch locale - short month name
  src/locale/nl/_lib/localize/index.js
Labels: I18n

#648 Fix typo
  docs/i18n.md
Labels: Docs

#624 update zh-CN locale
  src/locale/zh-CN/_lib/formatLong/index.js
  src/locale/zh-CN/_lib/formatRelative/index.js
  src/locale/zh-CN/_lib/match/index.js
Labels: I18n, ⛴ Ship it!

#727 Japanese translations
  src/locale/ja/_lib/formatLong/index.js
  src/locale/ja/_lib/formatRelative/index.js
  src/locale/ja/_lib/localize/index.js
  src/locale/ja/index.js
Labels: I18n, ⛴ Ship it!

#632 Et locale
  src/locale/et/_lib/formatDistance/index.js
  src/locale/et/_lib/formatDistance/test.js
  src/locale/et/_lib/formatLong/index.js
  src/locale/et/_lib/formatRelative/index.js
  src/locale/et/_lib/localize/index.js
  src/locale/et/_lib/match/index.js
  src/locale/et/index.d.ts
  src/locale/et/index.js
  src/locale/et/index.js.flow
  src/locale/et/test.js
Labels: I18n, ⛴ Ship it!

#645 add georgian (ka) language
  src/locale/ka/_lib/formatDistance/index.js
  src/locale/ka/_lib/formatDistance/test.js
  src/locale/ka/_lib/formatLong/index.js
  src/locale/ka/_lib/formatRelative/index.js
  src/locale/ka/_lib/localize/index.js
  src/locale/ka/_lib/match/index.js
  src/locale/ka/index.d.ts
  src/locale/ka/index.js
  src/locale/ka/index.js.flow
  src/locale/ka/test.js
Labels: I18n

#675 Add an af (Afrikaans) locale.
  src/locale/af/_lib/formatDistance/index.js
  src/locale/af/_lib/formatDistance/test.js
  src/locale/af/_lib/formatLong/index.js
  src/locale/af/_lib/formatRelative/index.js
  src/locale/af/_lib/localize/index.js
  src/locale/af/_lib/match/index.js
  src/locale/af/index.d.ts
  src/locale/af/index.js
  src/locale/af/index.js.flow
  src/locale/af/test.js
Labels: I18n, ⛴ Ship it!

#696 Locale sr latn
  src/locale/sr-Latn/_lib/formatDistance/index.js
  src/locale/sr-Latn/_lib/formatDistance/test.js
  src/locale/sr-Latn/_lib/formatLong/index.js
  src/locale/sr-Latn/_lib/formatRelative/index.js
  src/locale/sr-Latn/_lib/formatters/index.js
  src/locale/sr-Latn/_lib/localize/index.js
  src/locale/sr-Latn/_lib/match/index.js
  src/locale/sr-Latn/index.d.ts
  src/locale/sr-Latn/index.js
  src/locale/sr-Latn/index.js.flow
  src/locale/sr-Latn/test.js
Labels: I18n, ⛴ Ship it!

#690 Fixed issue when parsing ISO style dates (but not valid ISO format) with a trailing Z (Issue #510)
  CHANGELOG.md
  src/toDate/index.js
  src/toDate/test.js
Labels: Bug, ⛴ Ship it!

#735 Fix submodule sideEffects flags
  scripts/build/templates/subModulePackage.json
  scripts/build/templates/subSubModulePackage.json
  scripts/build/templates/subSubSubModulePackage.json
Labels: ⛴ Ship it!
