Repository date-fns/date-fns, pull requests merged in 2019-06, with the labels that each got.

#1161 Fix example comment to match example functionality
  src/formatDistanceStrict/index.js
Labels: 📃 Docs

#1124 fix wrong api doc
  src/differenceInCalendarDays/index.js
  src/differenceInDays/index.js
  src/format/index.js.flow
  src/index.js.flow
  src/parse/index.js.flow
  typings.d.ts
Labels: 📃 Docs

#1089 Correct documentation for `lightFormat`
  src/_lib/format/lightFormatters/index.js
  src/lightFormat/index.js
Labels: 📃 Docs

#586 Update docs to replace date-fns' CDN with cdnjs
  docs/getting_started.md
Labels: 👴 v1, 📃 Docs

#1140 Update pl locale to v2 format
  outdatedLocales.json
  src/esm/locale/index.js
  src/locale/index.js
  src/locale/pl/_lib/formatDistance/index.js
  src/locale/pl/_lib/formatDistance/test.js
  src/locale/pl/_lib/formatLong/index.js
  src/locale/pl/_lib/formatRelative/index.js
  src/locale/pl/_lib/localize/index.js
  src/locale/pl/_lib/match/index.js
  src/locale/pl/index.js
  src/locale/pl/test.js
Labels: 🌏 I18n

#1105 Update formatLong for DE locale
  src/locale/de/_lib/formatLong/index.js
  src/locale/de/test.js
Labels: 🌏 I18n

#1100 Add ko locale
  outdatedLocales.json
  src/locale/ko/_lib/formatLong/index.js
  src/locale/ko/_lib/formatRelative/index.js
  src/locale/ko/_lib/localize/index.js
  src/locale/ko/_lib/localize/test.js
  src/locale/ko/_lib/match/index.js
  src/locale/ko/_lib/match/test.js
  src/locale/ko/index.js
  src/locale/ko/test.js
Labels: 🌏 I18n

#1098 Improve Japanese translation of formatRelative()
  src/locale/ja/_lib/formatRelative/index.js
Labels: 🌏 I18n

#1090 Slovak locale v2 🎉
  src/locale/sk/_lib/formatDistance/index.js
  src/locale/sk/_lib/formatDistance/test.js
  src/locale/sk/_lib/formatLong/index.js
  src/locale/sk/_lib/formatRelative/index.js
  src/locale/sk/_lib/localize/index.js
  src/locale/sk/_lib/match/index.js
  src/locale/sk/index.js
  src/locale/sk/test.js
Labels: 🌏 I18n

#1168 Adding the ar-DZ for version 2
  src/locale/ar-DZ/_lib/formatDistance/index.js
  src/locale/ar-DZ/_lib/formatDistance/test.js
  src/locale/ar-DZ/_lib/formatLong/index.js
  src/locale/ar-DZ/_lib/formatRelative/index.js
  src/locale/ar-DZ/_lib/localize/index.js
  src/locale/ar-DZ/_lib/match/index.js
  src/locale/ar-DZ/index.js
  src/locale/ar-DZ/test.js
Labels: 🌏 I18n

#1113 Add Persian locale (fa-IR) for v2
  src/esm/locale/index.js
  src/locale/fa-IR/_lib/formatDistance/index.js
  src/locale/fa-IR/_lib/formatDistance/test.js
  src/locale/fa-IR/_lib/formatLong/index.js
  src/locale/fa-IR/_lib/formatRelative/index.js
  src/locale/fa-IR/_lib/localize/index.js
  src/locale/fa-IR/_lib/match/index.js
  src/locale/fa-IR/index.d.ts
  src/locale/fa-IR/index.js
  src/locale/fa-IR/index.js.flow
  src/locale/fa-IR/test.js
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: 🌏 I18n

#1183 Swedish short date format
  src/locale/sv/_lib/formatLong/index.js
  src/locale/sv/test.js
Labels: 🌏 I18n

#1130 Treat invalid time as InvalidDate in parseISO
  src/parseISO/index.js
  src/parseISO/test.js
Labels: 🌟 Improvement

#1107 Turkish locale v2
  src/locale/tr/_lib/formatDistance/index.js
  src/locale/tr/_lib/formatDistance/test.js
  src/locale/tr/_lib/formatLong/index.js
  src/locale/tr/_lib/formatRelative/index.js
  src/locale/tr/_lib/localize/index.js
  src/locale/tr/_lib/match/index.js
  src/locale/tr/index.js
  src/locale/tr/test.js
Labels: 🌏 I18n

#1070 Fix pt-BR translation
  src/locale/pt-BR/_lib/localize/index.js
  src/locale/pt-BR/_lib/match/index.js
  src/locale/pt-BR/test.js
Labels: 🌏 I18n

#1071 Convert da locale to v2 (closes #1061)
  outdatedLocales.json
  src/esm/locale/index.js
  src/locale/da/_lib/formatDistance/index.js
  src/locale/da/_lib/formatDistance/test.js
  src/locale/da/_lib/formatLong/index.js
  src/locale/da/_lib/formatRelative/index.js
  src/locale/da/_lib/localize/index.js
  src/locale/da/_lib/match/index.js
  src/locale/da/index.js
  src/locale/da/test.js
  src/locale/index.js
Labels: 🌏 I18n

#1049 Add BE locale
  src/locale/be/_lib/formatDistance/index.js
  src/locale/be/_lib/formatDistance/test.js
  src/locale/be/_lib/formatLong/index.js
  src/locale/be/_lib/formatRelative/index.js
  src/locale/be/_lib/localize/index.js
  src/locale/be/_lib/match/index.js
  src/locale/be/build_distance_in_words_locale/index.js
  src/locale/be/build_distance_in_words_locale/test.js
  src/locale/be/build_format_locale/index.js
  src/locale/be/build_format_locale/test.js
  src/locale/be/index.js
  src/locale/be/test.js
Labels: 🌏 I18n

#1053 Update Catalan locales
  src/locale/ca/_lib/formatLong/index.js
  src/locale/ca/_lib/formatRelative/index.js
  src/locale/ca/_lib/localize/index.js
  src/locale/ca/_lib/match/index.js
  src/locale/ca/index.js
  src/locale/ca/test.js
Labels: 🌏 I18n

#1080 Adding Uighur Locale
  src/locale/ui/_lib/formatDistance/index.js
  src/locale/ui/_lib/formatDistance/test.js
  src/locale/ui/_lib/formatLong/index.js
  src/locale/ui/_lib/formatRelative/index.js
  src/locale/ui/_lib/localize/index.js
  src/locale/ui/_lib/match/index.js
  src/locale/ui/index.d.ts
  src/locale/ui/index.js
  src/locale/ui/index.js.flow
  src/locale/ui/test.js
Labels: 🌏 I18n

#1050 Improve japanese translation of formatDistance with addSuffix option
  src/locale/ja/_lib/formatDistance/index.js
  src/locale/ja/_lib/formatDistance/test.js
Labels: 🌏 I18n

#1091 [Locale/zh-CN] change the ordinalNumber function
  src/locale/is/_lib/formatRelative/index.js
  src/locale/is/_lib/localize/index.js
  src/locale/is/_lib/match/index.js
  src/locale/zh-CN/_lib/localize/index.js
  src/locale/zh-CN/test.js
Labels: 🌏 I18n

#1186 Remove zh-TW from outdatedLocales.json
  outdatedLocales.json
Labels: 🌏 I18n

#1187 Add coverage report
  .gitignore
  .travis.yml
  config/karma.js
  config/webpack.js
  package.json
  scripts/test/coverageReport.sh
  yarn.lock
Labels: ⚙️ Chore

#1191 Update Yarn to the latest version (closes #883)
  .travis.yml
  package.json
  scripts/build/package.sh
  scripts/test/travis.sh
  scripts/test/tz.sh
  scripts/test/tzExtended.sh
Labels: ⚙️ Chore

#1189 Add p+ token support to parse function
  src/parse/index.js
  src/parse/test.js
  yarn.lock
Labels: 🌏 I18n, 🌟 Improvement

#1194 Add new feature differenceInBusinessDays
  CHANGELOG.md
  src/differenceInBusinessDays/index.d.ts
  src/differenceInBusinessDays/index.js
  src/differenceInBusinessDays/index.js.flow
  src/differenceInBusinessDays/test.js
  src/esm/fp/index.js
  src/esm/index.js
  src/fp/differenceInBusinessDays/index.d.ts
  src/fp/differenceInBusinessDays/index.js
  src/fp/differenceInBusinessDays/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: 🎉 Feature

#1154 Add new feature addBusinessDays
  CHANGELOG.md
  scripts/test/dst.sh
  src/addBusinessDays/index.d.ts
  src/addBusinessDays/index.js
  src/addBusinessDays/index.js.flow
  src/addBusinessDays/test.js
  src/esm/fp/index.js
  src/esm/index.js
  src/fp/addBusinessDays/index.d.ts
  src/fp/addBusinessDays/index.js
  src/fp/addBusinessDays/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/index.js
  src/index.js.flow
  test/dst/addBusinessDays/basic.js
  typings.d.ts
Labels: 🎉 Feature

#1125 CS locale
  config/karma.js
  src/locale/cs/_lib/formatDistance/index.js
  src/locale/cs/_lib/formatDistance/test.js
  src/locale/cs/_lib/formatLong/index.js
  src/locale/cs/_lib/formatRelative/index.js
  src/locale/cs/_lib/localize/index.js
  src/locale/cs/_lib/match/index.js
  src/locale/cs/index.js
  src/locale/cs/test.js
  src/locale/de/_lib/formatLong/index.js
  src/locale/ja/_lib/formatDistance/index.js
  src/locale/ja/_lib/formatDistance/test.js
  src/locale/pt-BR/_lib/localize/index.js
  src/locale/pt-BR/_lib/match/index.js
Labels: 🌏 I18n

#1203 Remove outdated locales from the package (closes #1014)
  package.json
  scripts/build/package.sh
  scripts/build/removeOutdatedLocales.js
Labels: 🌏 I18n

#1205 Update CONTRIBUTING.md to reflect changes to 'toDate' in v2
  CONTRIBUTING.md
Labels: 📃 Docs

#1213 Add @babel/plugin-transform-template-literals (closes #1211)
  .babelrc.js
  package.json
  yarn.lock
Labels: 🌏 I18n, 🐛 Bug

#1215 Add @babel/plugin-transform-arrow-functions
  .babelrc.js
  package.json
  yarn.lock
Labels: 🌏 I18n, 🐛 Bug

#1212 Fix package name
  docs/timeZones.md
Labels: ☠️ Won't fix

#1217 Add missing case declension to Czech locale
  outdatedLocales.json
  src/locale/cs/_lib/formatRelative/index.js
  src/locale/cs/_lib/localize/index.js
  src/locale/cs/_lib/match/index.js
  src/locale/cs/snapshot.md
Labels: 🌏 I18n
