Repository date-fns/date-fns, pull requests merged in 2019-07, with the labels that each got.

#1233 fix(typings): export interface
  scripts/build/_lib/typings/typeScript.js
Labels: TypeScript

#1256 Revert "fix(typings): export interface"
  scripts/build/_lib/typings/typeScript.js
Labels: ⚙️ Chore

#1254 Feature/1156 Cymraeg Locale
  src/locale/cy/_lib/formatDistance/index.js
  src/locale/cy/_lib/formatLong/index.js
  src/locale/cy/_lib/formatRelative/index.js
  src/locale/cy/_lib/localize/index.js
  src/locale/cy/_lib/match/index.js
  src/locale/cy/index.d.ts
  src/locale/cy/index.js
  src/locale/cy/index.js.flow
  src/locale/cy/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: 🌏 I18n
