Repository date-fns/date-fns, pull requests merged in 2019-08, with the labels that each got.

#1269 fix: incorrect response for dates falling on weekends (differenceInBusinessDays)
  src/differenceInBusinessDays/index.js
  src/differenceInBusinessDays/test.js
Labels: 🐛 Bug

#1264 fix: fix TS typings for curried functions
  scripts/build/_lib/typings/typeScript.js
  typings.d.ts
Labels: TypeScript, ⛴ Ship it!

#1258 min/max: return Invalid Date for all invalid inputs
  src/max/index.js
  src/max/test.js
  src/min/index.js
  src/min/test.js
Labels: 😈 Breaking

#1280 Fix example format
  README.md
Labels: 📃 Docs

#1270 Updated Croatian (hr) locale for v2
  outdatedLocales.json
  src/locale/hr/_lib/formatLong/index.js
  src/locale/hr/_lib/formatRelative/index.js
  src/locale/hr/_lib/formatters/index.js
  src/locale/hr/_lib/localize/index.js
  src/locale/hr/_lib/match/index.js
  src/locale/hr/index.js
  src/locale/hr/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🚧 Needs build run

#1288 Fix minor styling issue in typings build scripts
  scripts/build/_lib/typings/flow.js
  scripts/build/_lib/typings/typeScript.js
Labels: ⚙️ Chore

#1295 Remove v2 notice (closes #1267)
  docs/printV2Notice.js
  package.json
Labels: ⚙️ Chore

#1289 fix CA spelling errors and update following official gramatical rules
  outdatedLocales.json
  src/locale/ca/_lib/formatDistance/index.js
  src/locale/ca/_lib/localize/index.js
  src/locale/ca/_lib/match/index.js
  src/locale/ca/snapshot.md
  src/locale/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1286 addBusinessDays negative amount fix, performance fixes for addBusinessDays and differenceInBusinessDays
  src/addBusinessDays/index.js
  src/addBusinessDays/test.js
  src/differenceInBusinessDays/index.js
  src/differenceInBusinessDays/test.js
Labels: ⛴ Ship it!, 🌟 Improvement, 🐛 Bug

#1046 fixed issue: options.weekStartsOn set to 1 doesn't work for Sundays
  src/getWeekOfMonth/index.js
  src/getWeekOfMonth/test.js
Labels: 🐛 Bug
