Repository date-fns/date-fns, pull requests merged in 2019-10, with the labels that each got.

#1462 [CS] Change to use 24H time format
  src/locale/cs/_lib/formatLong/index.js
  src/locale/cs/snapshot.md
Labels: 🌏 I18n

#1482 fix i18n.md broken TOC link
  docs/i18n.md
Labels: 📃 Docs

#1481 Chore - fix Karma warning for webpack build
  config/webpack.js
Labels: ⚙️ Chore

#1457 Remove findIndex from codebase - compat with IE11
  src/locale/_lib/buildMatchFn/index.js
Labels: ⛴ Ship it!

#1460 Add Kazakh language 🇰🇿
  src/locale/kk/_lib/formatDistance/index.js
  src/locale/kk/_lib/formatLong/index.js
  src/locale/kk/_lib/formatRelative/index.js
  src/locale/kk/_lib/localize/index.js
  src/locale/kk/_lib/match/index.js
  src/locale/kk/index.js
  src/locale/kk/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1464 Add Telugu language
  src/locale/index.js
  src/locale/index.js.flow
  src/locale/te/_lib/formatDistance/index.js
  src/locale/te/_lib/formatLong/index.js
  src/locale/te/_lib/formatRelative/index.js
  src/locale/te/_lib/localize/index.js
  src/locale/te/_lib/match/index.js
  src/locale/te/index.d.ts
  src/locale/te/index.js
  src/locale/te/index.js.flow
  src/locale/te/snapshot.md
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1471 Updated isValid() example, refs #1461
  src/isValid/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1479 Add fr-CA locale
  src/locale/fr-CA/_lib/formatLong/index.js
  src/locale/fr-CA/index.d.ts
  src/locale/fr-CA/index.js
  src/locale/fr-CA/index.js.flow
  src/locale/fr-CA/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1480 Improve / fix greek locale patterns
  src/locale/el/_lib/match/index.js
  src/locale/el/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1470 Add en-AU
  src/locale/en-AU/_lib/formatLong/index.js
  src/locale/en-AU/index.d.ts
  src/locale/en-AU/index.js
  src/locale/en-AU/index.js.flow
  src/locale/en-AU/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: 🌏 I18n

#1486 Fix addBusinessDays for weekends
  src/addBusinessDays/index.js
Labels: ⚠️ Important, 🐛 Bug

#1492 Upgrade Node.js to v12 on Travis CI
  .travis.yml
Labels: ⚙️ Chore

#1463 parseJSON - minimal implementation for parsing JSON dates from an API
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/parseJSON/index.d.ts
  src/fp/parseJSON/index.js
  src/fp/parseJSON/index.js.flow
  src/index.js
  src/index.js.flow
  src/parseJSON/benchmark.js
  src/parseJSON/index.d.ts
  src/parseJSON/index.js
  src/parseJSON/index.js.flow
  src/parseJSON/test.js
  typings.d.ts
Labels: ⛴ Ship it!, 🎉 Feature

#1491 Add subBusinessDays based on addBusinessDays
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/subBusinessDays/index.d.ts
  src/fp/subBusinessDays/index.js
  src/fp/subBusinessDays/index.js.flow
  src/index.js
  src/index.js.flow
  src/subBusinessDays/index.d.ts
  src/subBusinessDays/index.js
  src/subBusinessDays/index.js.flow
  src/subBusinessDays/test.js
  typings.d.ts
Labels: ⛴ Ship it!, 🎉 Feature
