Repository date-fns/date-fns, pull requests merged in 2019-09, with the labels that each got.

#1317 Remove v1-only date-fns-timezone from docs
  docs/timeZones.md
Labels: ⛴ Ship it!, 📃 Docs

#1400 Add Gujarati locale
  src/locale/gu/_lib/formatDistance/index.js
  src/locale/gu/_lib/formatLong/index.js
  src/locale/gu/_lib/formatRelative/index.js
  src/locale/gu/_lib/localize/index.js
  src/locale/gu/_lib/match/index.js
  src/locale/gu/index.d.ts
  src/locale/gu/index.js
  src/locale/gu/index.js.flow
  src/locale/gu/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1402 Update Thai locale first day of week
  src/locale/th/index.js
  src/locale/th/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1404 Change order inside Polish month matching pattern
  src/locale/pl/_lib/match/index.js
  src/locale/pl/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1407 Don't skip start date in eachWeekendOfInterval
  src/eachWeekendOfInterval/index.js
  src/eachWeekendOfInterval/test.js
Labels: ⚠️ Important, ⛴ Ship it!, 🐛 Bug

#1396 Fix broken internal-links of i18n contribution guide
  docs/i18nContributionGuide.md
Labels: ⛴ Ship it!, 📃 Docs

#1434 Fix Hindi parsing patterns
  src/locale/hi/_lib/match/index.js
  src/locale/hi/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1433 Fix march in Dutch parsing patterns
  src/locale/nl/_lib/match/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1431 Accept abbreviated march, june, july in Norwegian locales
  src/locale/nb/_lib/match/index.js
  src/locale/nb/snapshot.md
  src/locale/nn/_lib/match/index.js
  src/locale/nn/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1430 Fix French parsing issues with june and august
  src/locale/fr/_lib/match/index.js
  src/locale/fr/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1425 Add Finnish matching patterns
  src/locale/fi/_lib/match/index.js
  src/locale/fi/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1435 Add parsing for Greek months with long formatting
  src/locale/el/_lib/match/index.js
  src/locale/el/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1450 Fix offset for Eastern Hemisphere in parseISO, fixes #1449, fixes #1119
  scripts/test/dst.sh
  src/parseISO/index.js
  test/dst/parseISO/sydney.js
Labels: ⛴ Ship it!, 🐛 Bug

#1448 Add Armenian language support
  src/locale/hy/_lib/formatDistance/index.js
  src/locale/hy/_lib/formatLong/index.js
  src/locale/hy/_lib/formatRelative/index.js
  src/locale/hy/_lib/localize/index.js
  src/locale/hy/_lib/match/index.js
  src/locale/hy/index.js
  src/locale/hy/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1446 Fix Czech parsing regexes
  src/locale/cs/_lib/match/index.js
  src/locale/cs/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1445 Fix Vietnamese parsing patterns
  src/locale/vi/_lib/match/index.js
  src/locale/vi/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1441 Add v1 pattern column to format table for 2.0.0
  CHANGELOG.md
Labels: ⛴ Ship it!, 📃 Docs
