Repository date-fns/date-fns, pull requests merged in 2019-11, with the labels that each got.

#1534 Bump jsdoc-to-markdown
  package.json
  yarn.lock
Labels: ⛴ Ship it!

#1529 Fix mistake in Slovenian translation
  src/locale/sl/_lib/formatDistance/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1505 areIntervalsOverlapping: improve doc
  src/areIntervalsOverlapping/index.js
Labels: ⛴ Ship it!

#1516 roundToNearestMinutes: improve jsdoc
  src/roundToNearestMinutes/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1519 In generated types, give objects more verbose types
  scripts/build/_lib/typings/common.js
  src/fp/differenceInCalendarWeeksWithOptions/index.js.flow
  src/fp/eachDayOfIntervalWithOptions/index.js.flow
  src/fp/eachWeekOfIntervalWithOptions/index.js.flow
  src/fp/endOfDecadeWithOptions/index.js.flow
  src/fp/endOfWeekWithOptions/index.js.flow
  src/fp/formatDistanceStrictWithOptions/index.js.flow
  src/fp/formatDistanceWithOptions/index.js.flow
  src/fp/formatRelativeWithOptions/index.js.flow
  src/fp/formatWithOptions/index.js.flow
  src/fp/getWeekOfMonthWithOptions/index.js.flow
  src/fp/getWeekWithOptions/index.js.flow
  src/fp/getWeekYearWithOptions/index.js.flow
  src/fp/getWeeksInMonthWithOptions/index.js.flow
  src/fp/index.js.flow
  src/fp/isSameWeekWithOptions/index.js.flow
  src/fp/lastDayOfQuarterWithOptions/index.js.flow
  src/fp/lastDayOfWeekWithOptions/index.js.flow
  src/fp/parseISOWithOptions/index.js.flow
  src/fp/parseWithOptions/index.js.flow
  src/fp/roundToNearestMinutesWithOptions/index.js.flow
  src/fp/set/index.js.flow
  src/fp/setDayWithOptions/index.js.flow
  src/fp/setWeekWithOptions/index.js.flow
  src/fp/setWeekYearWithOptions/index.js.flow
  src/fp/startOfWeekWithOptions/index.js.flow
  src/fp/startOfWeekYearWithOptions/index.js.flow
  typings.d.ts
Labels: Flow, Hacktoberfest, TypeScript, ⚙️ Chore, ⛴ Ship it!

#1522 Enable Bulgarian i18n
  outdatedLocales.json
  src/locale/bg/_lib/formatLong/index.js
  src/locale/bg/_lib/formatRelative/index.js
  src/locale/bg/_lib/localize/index.js
  src/locale/bg/_lib/match/index.js
  src/locale/bg/index.js
  src/locale/bg/snapshot.md
  src/locale/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1495 [1310] round timezones offset in milliseconds
  src/_lib/getTimezoneOffsetInMilliseconds/index.js
Labels: ⛴ Ship it!

#1499 Allow `parseJSON` to accept strings without a trailing 'Z' symbold and with up to 6 digits in the milliseconds field (#1496)
  src/parseJSON/index.js
  src/parseJSON/test.js
Labels: ⛴ Ship it!

#1501 isWithinInterval: details about bound inclusion
  src/isWithinInterval/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1535 differenceInMinutes: improve JSdoc
  src/differenceInMinutes/index.js
Labels: ⛴ Ship it!

#1537 Update Malay locale for v2
  outdatedLocales.json
  src/locale/ms/_lib/formatLong/index.js
  src/locale/ms/_lib/formatRelative/index.js
  src/locale/ms/_lib/localize/index.js
  src/locale/ms/_lib/match/index.js
  src/locale/ms/index.js
  src/locale/ms/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1538 Remove next week preposition for Swedish locale
  src/locale/sv/_lib/formatRelative/index.js
  src/locale/sv/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#618 Added eachYear, eachMonth, eachWeek #540
  src/eachMonthOfInterval/index.d.ts
  src/eachMonthOfInterval/index.js
  src/eachMonthOfInterval/index.js.flow
  src/eachMonthOfInterval/test.js
  src/eachYearOfInterval/index.d.ts
  src/eachYearOfInterval/index.js
  src/eachYearOfInterval/index.js.flow
  src/eachYearOfInterval/test.js
  src/fp/eachMonthOfInterval/index.d.ts
  src/fp/eachMonthOfInterval/index.js
  src/fp/eachMonthOfInterval/index.js.flow
  src/fp/eachYearOfInterval/index.d.ts
  src/fp/eachYearOfInterval/index.js
  src/fp/eachYearOfInterval/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: 🎉 Feature
