Repository date-fns/date-fns, pull requests merged in 2020-04, with the labels that each got.

#1701 Fix minulý štvrtok in Slovak locale (fixes #1699)
  src/locale/sk/_lib/formatRelative/index.js
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1690 Fix date ordinalNumber for ja/zh-CN/zh-TW
  src/locale/ja/_lib/localize/index.js
  src/locale/ja/_lib/match/index.js
  src/locale/ja/index.js
  src/locale/ja/snapshot.md
  src/locale/zh-CN/_lib/localize/index.js
  src/locale/zh-CN/_lib/match/index.js
  src/locale/zh-CN/index.js
  src/locale/zh-CN/snapshot.md
  src/locale/zh-TW/_lib/localize/index.js
  src/locale/zh-TW/_lib/match/index.js
  src/locale/zh-TW/index.js
  src/locale/zh-TW/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1694 Fixes #1650 - locale was parsing wrong string after matching the pat…
  src/locale/_lib/buildMatchFn/index.js
  src/parse/test.js
Labels: ⛴ Ship it!

#1674 Fix requiredArgs error message
  src/_lib/requiredArgs/index.js
  src/_lib/requiredArgs/test.js
Labels: ⛴ Ship it!, 🐛 Bug

#1696 Fix ordinal number for ja/ko
  src/locale/ja/index.js
  src/locale/ko/_lib/localize/index.js
  src/locale/ko/_lib/match/index.js
  src/locale/ko/index.js
  src/locale/ko/snapshot.md
Labels: 🌏 I18n

#1639 Fix issue #1637: setDay with weekStartsOn != 0
  CHANGELOG.md
  src/setDay/index.js
  src/setDay/test.js
Labels: ⛴ Ship it!, 🐛 Bug

#1630 fix differenceInDays across DST (#533)
  src/differenceInDays/index.js
  src/differenceInDays/test.js
Labels: ⛴ Ship it!
