Repository date-fns/date-fns, pull requests merged in 2020-03, with the labels that each got.

#1662 Correct typo: ISO1806 to ISO8601
  src/parseJSON/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1648 added UZ locale
  src/locale/uz/_lib/formatDistance/index.js
  src/locale/uz/_lib/formatLong/index.js
  src/locale/uz/_lib/formatRelative/index.js
  src/locale/uz/_lib/localize/index.js
  src/locale/uz/_lib/match/index.js
  src/locale/uz/index.js
  src/locale/uz/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1649 Update Macedonian locale. Fixes #1531
  outdatedLocales.json
  src/locale/mk/_lib/formatDistance/index.js
  src/locale/mk/_lib/formatLong/index.js
  src/locale/mk/_lib/formatRelative/index.js
  src/locale/mk/_lib/localize/index.js
  src/locale/mk/_lib/match/index.js
  src/locale/mk/index.js
  src/locale/mk/snapshot.md
Labels: ⛴ Ship it!

#1654 Fix issue: #1642 - differenceInYears leap day fix
  src/differenceInYears/index.js
  src/differenceInYears/test.js
Labels: ⛴ Ship it!

#1658 Add mt locale support
  src/locale/index.js
  src/locale/index.js.flow
  src/locale/mt/_lib/formatDistance/index.js
  src/locale/mt/_lib/formatLong/index.js
  src/locale/mt/_lib/formatRelative/index.js
  src/locale/mt/_lib/localize/index.js
  src/locale/mt/_lib/match/index.js
  src/locale/mt/index.d.ts
  src/locale/mt/index.js
  src/locale/mt/index.js.flow
  src/locale/mt/snapshot.md
  typings.d.ts
Labels: 🌏 I18n

#1667 Fix parseISO around time shift dates, fixes #1618
  src/parseISO/index.js
  test/dst/parseISO/sydney.js
Labels: 🐛 Bug

#1664 fix bug in fn formatRelative: next/last prefix shows depends on the day in same week or not
  scripts/build/localeSnapshots/renderFormatDistance/index.js
  scripts/build/localeSnapshots/renderFormatDistanceStrict/index.js
  scripts/build/localeSnapshots/renderFormatParse/index.js
  scripts/build/localeSnapshots/renderFormatRelative/index.js
  src/_lib/getUTCWeekYear/index.js
  src/_lib/startOfUTCWeekYear/index.js
  src/locale/ar-MA/index.js
  src/locale/hr/_lib/formatLong/index.js
  src/locale/hr/_lib/match/index.js
  src/locale/zh-CN/_lib/formatRelative/index.js
  src/locale/zh-CN/snapshot.md
  src/max/test.js
  src/min/test.js
  src/parse/index.js
  src/parse/test.js
  src/roundToNearestMinutes/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1666 Fixed timezone offset getting for UTC-n timezones
  src/_lib/getTimezoneOffsetInMilliseconds/index.js
Labels: 🐛 Bug
