Repository date-fns/date-fns, pull requests merged in 2020-10, with the labels that each got.

#1964 Migrate: addMiliseconds to TS
  src/addMilliseconds/index.ts
  src/addMilliseconds/test.ts
Labels: TypeScript

#1970 Migrate to TS: subYears
  src/subYears/index.ts
  src/subYears/test.ts
Labels: TypeScript

#1971 Migrate to TS: subWeeks
  src/subWeeks/index.ts
  src/subWeeks/test.ts
Labels: TypeScript

#1979 Migrate to TS: subSeconds
  src/subSeconds/index.ts
  src/subSeconds/test.ts
Labels: TypeScript

#1980 Migrate to TS: subQuarters
  src/subQuarters/index.ts
  src/subQuarters/test.ts
Labels: TypeScript

#2002 Migrate to TS: subDays
  src/subDays/index.ts
  src/subDays/test.ts
Labels: TypeScript

#1995 Migrate to TS: subHours
  src/subHours/index.ts
  src/subHours/test.ts
Labels: TypeScript

#1991 Migrate to TS: subMilliseconds
  src/subMilliseconds/index.ts
  src/subMilliseconds/test.ts
Labels: TypeScript

#1993 Migration to TS: getDays Functions
  src/getDate/index.ts
  src/getDate/test.ts
  src/getDay/index.ts
  src/getDay/test.ts
  src/getDayOfYear/index.ts
  src/getDayOfYear/test.ts
  src/getDaysInMonth/index.ts
  src/getDaysInMonth/test.ts
  src/getDaysInYear/index.ts
  src/getDaysInYear/test.ts
Labels: TypeScript

#1990 Migrate to TS: subMinutes
  src/subMinutes/index.ts
  src/subMinutes/test.ts
Labels: TypeScript

#1994 Migrate to TS: subISOWeekYears
  src/subISOWeekYears/index.ts
  src/subISOWeekYears/test.ts
Labels: TypeScript

#1985 Update docs to make localised date formats clearer
  src/format/index.js
Labels: 📃 Docs

#1963 Improvement: minor changes in previous migrations
  src/add/index.ts
  src/add/test.ts
  src/addBusinessDays/index.ts
  src/addBusinessDays/test.ts
  src/addDays/index.ts
  src/addDays/test.ts
  src/addHours/index.ts
  src/addHours/test.ts
  src/addISOWeekYears/index.ts
  src/addMinutes/index.ts
  src/addMonths/index.ts
  src/addQuarters/index.ts
  src/addSeconds/index.ts
  src/addWeeks/index.ts
  src/addYears/index.ts
Labels: TypeScript

#2015 Migrate eachDayOfInterval function to typescript
  src/eachDayOfInterval/index.ts
  src/eachDayOfInterval/test.ts
Labels: TypeScript migration

#1950 Fix russian locale parsing issue
  src/locale/ru/_lib/match/index.js
  src/locale/ru/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1952 Add en-ZA support
  src/locale/en-ZA/_lib/formatLong/index.js
  src/locale/en-ZA/index.d.ts
  src/locale/en-ZA/index.js
  src/locale/en-ZA/index.js.flow
  src/locale/en-ZA/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#2026 Migrate to TS: eachWeekendOfMonth
  src/eachWeekendOfMonth/index.ts
  src/eachWeekendOfMonth/test.ts
Labels: TypeScript migration

#2025 Migrate to TS: eachWeekendOfInterval
  src/eachWeekendOfInterval/index.ts
  src/eachWeekendOfInterval/test.ts
Labels: TypeScript migration

#2017 Migrate to TS: eachHourOfInterval
  src/eachHourOfInterval/index.ts
  src/eachHourOfInterval/test.ts
Labels: TypeScript migration

#2018 Migrate to TS:eachMonthOfInterval
  src/eachMonthOfInterval/index.ts
  src/eachMonthOfInterval/test.ts
Labels: TypeScript migration

#2020 Migrate to TS: eachWeekOfInterval
  src/eachWeekOfInterval/index.ts
  src/eachWeekOfInterval/test.ts
Labels: TypeScript migration

#2019 Migrate to TS:eachQuarterOfInterval
  src/eachQuarterOfInterval/index.ts
  src/eachQuarterOfInterval/test.ts
Labels: TypeScript migration

#1981 Migrate to TS: subMonths
  src/subMonths/index.ts
  src/subMonths/test.ts
Labels: TypeScript migration

#2062 Migrate endOfWeek function to TS
  src/endOfWeek/index.ts
  src/endOfWeek/test.ts
Labels: TypeScript migration
