Repository date-fns/date-fns, pull requests merged in 2020-01, with the labels that each got.

#1556 Bump TypeScript to 3.7.2
  examples/typescript/package.json
  examples/typescript/yarn.lock
  package.json
  yarn.lock
Labels: ⚙️ Chore

#1581 Feature/implement generic add
  CHANGELOG.md
  src/add/benchmark.js
  src/add/index.d.ts
  src/add/index.js
  src/add/index.js.flow
  src/add/test.js
  src/fp/add/index.d.ts
  src/fp/add/index.js
  src/fp/add/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🎉 Feature

#1512 update day values for Kazakh language
  src/locale/kk/_lib/localize/index.js
  src/locale/kk/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1540 Fix typo in Czech locale (formatDistance)
  src/locale/cs/_lib/formatDistance/index.js
  src/locale/cs/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1547 Add Azerbaijani language az
  src/locale/az/_lib/formatDistance/index.js
  src/locale/az/_lib/formatLong/index.js
  src/locale/az/_lib/formatRelative/index.js
  src/locale/az/_lib/localize/index.js
  src/locale/az/_lib/match/index.js
  src/locale/az/index.d.ts
  src/locale/az/index.js
  src/locale/az/index.js.flow
  src/locale/az/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1560 Fix widths in bg locale
  src/locale/bg/_lib/localize/index.js
  src/locale/bg/_lib/match/index.js
  src/locale/bg/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1565 fix(locale): fix parsing regex for month may of locale pt
  src/locale/pt/_lib/match/index.js
  src/locale/pt/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1578 Add ar-MA locale support
  src/locale/ar-MA/_lib/formatDistance/index.js
  src/locale/ar-MA/_lib/formatLong/index.js
  src/locale/ar-MA/_lib/formatRelative/index.js
  src/locale/ar-MA/_lib/localize/index.js
  src/locale/ar-MA/_lib/match/index.js
  src/locale/ar-MA/index.js
  src/locale/ar-MA/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1579 parseJSON supports a space time separator for SQL datetime
  src/parseJSON/index.js
  src/parseJSON/test.js
Labels: ⛴ Ship it!, 🌟 Improvement

#1576 Add timezone to formatISO
  src/formatISO/index.js
  src/formatISO/test.js
Labels: ⛴ Ship it!, 🌟 Improvement

#1594 Fix documentation examples for eachYearOfInterval and eachMonthOfInterval
  src/eachMonthOfInterval/index.js
  src/eachYearOfInterval/index.js
Labels: 📃 Docs
