Repository date-fns/date-fns, pull requests merged in 2020-07, with the labels that each got.

#1803 docs: fix English in unicodeTokens
  docs/unicodeTokens.md
Labels: 📃 Docs

#1847 Add index information to `getDay` docs
  src/getDay/index.js
Labels: 📃 Docs

#1824 Unescaped single quotes in timeZones.md docs file
  docs/timeZones.md
Labels: 📃 Docs

#1820 Fix engines
  package.json
Labels: ⚙️ Chore

#1817 Fix formatting in parseJSON documentation
  src/parseJSON/index.js
Labels: 📃 Docs

#1875 Fix "Day of week" formatting documentation
  src/format/index.js
Labels: 📃 Docs

#1829 Add copyright to LICENSE.md
  LICENSE.md
Labels: 📃 Docs

#1790 Fix addBusinessDays when input date is a weekend day (#1628)
  src/addBusinessDays/index.js
  src/addBusinessDays/test.js
Labels: ⛴ Ship it!, 🐛 Bug

#1791 fix parseISO not returning Invalid Date when there are space(s) in passed string
  src/parseISO/index.js
  src/parseISO/test.js
Labels: ⛴ Ship it!, 🌏 I18n

#1792 Fix es round tripping dates with Wednesday
  src/locale/es/_lib/match/index.js
  src/locale/es/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1795 fix roundtrip bug with d/EEEE ordering in formats like PPPPP
  src/locale/hu/snapshot.md
  src/locale/hy/snapshot.md
  src/locale/ja/snapshot.md
  src/locale/ko/snapshot.md
  src/locale/lt/snapshot.md
  src/locale/te/snapshot.md
  src/locale/tr/snapshot.md
  src/locale/zh-CN/snapshot.md
  src/locale/zh-TW/snapshot.md
  src/parse/_lib/parsers/index.js
  src/parse/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1807 Fixing date parsing for Japanese
  src/locale/ja/_lib/match/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1809 Update Swiss-french (fr-CH) locale
  outdatedLocales.json
  src/locale/fr-CH/_lib/formatLong/index.js
  src/locale/fr-CH/_lib/formatRelative/index.js
  src/locale/fr-CH/_lib/localize/index.js
  src/locale/fr-CH/_lib/match/index.js
  src/locale/fr-CH/index.js
  src/locale/fr-CH/snapshot.md
  src/locale/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1812 Update Flemish (nl-BE) locale
  outdatedLocales.json
  src/locale/index.js
  src/locale/nl-BE/_lib/formatDistance/index.js
  src/locale/nl-BE/_lib/formatLong/index.js
  src/locale/nl-BE/_lib/formatRelative/index.js
  src/locale/nl-BE/_lib/localize/index.js
  src/locale/nl-BE/_lib/match/index.js
  src/locale/nl-BE/index.js
  src/locale/nl-BE/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1832 Add Scottish Gaelic support
  src/locale/gd/_lib/formatDistance/index.js
  src/locale/gd/_lib/formatLong/index.js
  src/locale/gd/_lib/formatRelative/index.js
  src/locale/gd/_lib/localize/index.js
  src/locale/gd/_lib/match/index.js
  src/locale/gd/index.d.ts
  src/locale/gd/index.js
  src/locale/gd/index.js.flow
  src/locale/gd/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1835 Feature en-NZ
  src/locale/en-NZ/_lib/formatLong/index.js
  src/locale/en-NZ/index.d.ts
  src/locale/en-NZ/index.js
  src/locale/en-NZ/index.js.flow
  src/locale/en-NZ/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1842 fix(HungarianLocale): Use IE 11 friendly syntax for object keys
  src/locale/hu/_lib/formatDistance/index.js
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1868 feat: add isMatch function
  src/isMatch/index.js
  src/isMatch/test.js
Labels: ⛴ Ship it!, 🎉 Feature
