Repository date-fns/date-fns, pull requests merged in 2020-08, with the labels that each got.

#1878 Correct pull request reference in CHANGELOG
  CHANGELOG.md
Labels: ⛴ Ship it!, 📃 Docs

#1884 Fix typo
  src/parse/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1905 Correct lightFormat usage example
  src/lightFormat/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1889 link to changelog
  docs/upgradeGuide.md
Labels: ⛴ Ship it!, 📃 Docs

#1891 Fix a dead link on Upgrade Guide
  docs/upgradeGuide.md
Labels: ⛴ Ship it!, 📃 Docs

#1903 Add correct translations for Welsh `1 minute` and `2 days`
  src/locale/cy/_lib/formatDistance/index.js
  src/locale/cy/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1890 Fix formatRFC3339: adjust formatting offset for timezones with minutes
  scripts/test/formatRFC3339.sh
  scripts/test/travis.sh
  src/formatRFC3339/index.js
  src/formatRFC3339/test.js
  test/formatRFC3339/australia.js
  test/formatRFC3339/india.js
  test/formatRFC3339/newfoundland.js
  test/formatRFC3339/newzealand.js
  test/formatRFC3339/poland.js
Labels: ⛴ Ship it!, 🐛 Bug

#1881 Missing locale type definition for formatDuration
  src/formatDuration/index.js
  src/formatDuration/index.js.flow
  src/fp/formatDurationWithOptions/index.js.flow
  src/fp/index.js.flow
  src/index.js.flow
  typings.d.ts
Labels: TypeScript, ⛴ Ship it!

#1900 Add Luxembourgish (lb) locale
  src/locale/lb/_lib/formatDistance/index.js
  src/locale/lb/_lib/formatLong/index.js
  src/locale/lb/_lib/formatRelative/index.js
  src/locale/lb/_lib/localize/index.js
  src/locale/lb/_lib/match/index.js
  src/locale/lb/index.js
  src/locale/lb/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1914 Fixes for Scottish Gaelic locale issues
  src/locale/gd/_lib/formatDistance/index.js
  src/locale/gd/_lib/localize/index.js
  src/locale/gd/_lib/match/index.js
  src/locale/gd/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1893 he locale: use shorter Hebrew alternative for "about"
  src/locale/he/_lib/formatDistance/index.js
  src/locale/he/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1910 Clarifies that strings are still allowed as arguments, but not when a date is expected
  docs/upgradeGuide.md
  src/toDate/index.js
  src/toDate/test.js
Labels: ⛴ Ship it!

#1928 Fix sr-Latn typos
  src/locale/sr-Latn/_lib/formatDistance/index.js
  src/locale/sr-Latn/_lib/localize/index.js
  src/locale/sr-Latn/_lib/match/index.js
  src/locale/sr-Latn/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug

#1925 Space should be after 'o chionn' not before
  src/locale/gd/_lib/formatDistance/index.js
  src/locale/gd/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n, 🐛 Bug, 🔥 Important

#1930 Fixed greek grammar for Saturday on formatRelative
  src/locale/el/_lib/formatRelative/index.js
Labels: 🌏 I18n
