Repository date-fns/date-fns, pull requests merged in 2020-05, with the labels that each got.

#1747 Added Kannada (India) locale support
  src/locale/index.js
  src/locale/index.js.flow
  src/locale/kn/_lib/formatDistance/index.js
  src/locale/kn/_lib/formatLong/index.js
  src/locale/kn/_lib/formatRelative/index.js
  src/locale/kn/_lib/localize/index.js
  src/locale/kn/_lib/match/index.js
  src/locale/kn/index.d.ts
  src/locale/kn/index.js
  src/locale/kn/index.js.flow
  src/locale/kn/snapshot.md
  typings.d.ts
Labels: ⛴ Ship it!

#1743 $ chmod -x CHANGELOG.md
  CHANGELOG.md
Labels: ⛴ Ship it!

#1713 Add `getISODurationString` function
  src/formatISODuration/index.d.ts
  src/formatISODuration/index.js
  src/formatISODuration/index.js.flow
  src/formatISODuration/test.js
  src/fp/formatISODuration/index.d.ts
  src/fp/formatISODuration/index.js
  src/fp/formatISODuration/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/fp/intervalToDuration/index.d.ts
  src/fp/intervalToDuration/index.js
  src/fp/intervalToDuration/index.js.flow
  src/index.js
  src/index.js.flow
  src/intervalToDuration/index.d.ts
  src/intervalToDuration/index.js
  src/intervalToDuration/index.js.flow
  src/intervalToDuration/test.js
  typings.d.ts
Labels: ⛴ Ship it!, 🎉 Feature

#1722 Fix code comments
  src/endOfTomorrow/index.js
  src/endOfYesterday/index.js
  src/startOfTomorrow/index.js
  src/startOfYesterday/index.js
Labels: ⛴ Ship it!

#1723 Fix wrong example
  src/format/index.js
  src/parse/index.js
Labels: ⛴ Ship it!, 📃 Docs

#1769 fix bad date initialization in test
  src/getYear/test.js
  src/set/test.js
Labels: ⚙️ Chore

#1773 Fix the differenceInDays example
  src/differenceInDays/index.js
Labels: 📃 Docs

#1759 Add Basque (eu) locale (closes #861)
  src/locale/eu/_lib/formatDistance/index.js
  src/locale/eu/_lib/formatLong/index.js
  src/locale/eu/_lib/formatRelative/index.js
  src/locale/eu/_lib/localize/index.js
  src/locale/eu/_lib/match/index.js
  src/locale/eu/index.d.ts
  src/locale/eu/index.js
  src/locale/eu/index.js.flow
  src/locale/eu/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#1760 Fix DST issues with add & addMonths
  CHANGELOG.md
  src/add/index.js
  src/add/test.js
  src/addDays/index.js
  src/addDays/test.js
  src/addMonths/index.js
  src/addMonths/test.js
Labels: ⛴ Ship it!, 🐛 Bug

#1763 Fix "quarter" translation in Bulgarian locale
  src/locale/bg/_lib/localize/index.js
  src/locale/bg/_lib/match/index.js
  src/locale/bg/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1765 Fix formatDistance strings in Hungarian locale
  src/locale/hu/_lib/formatDistance/index.js
  src/locale/hu/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1767 Added English (India) locale support
  src/locale/en-IN/_lib/formatLong/index.js
  src/locale/en-IN/index.d.ts
  src/locale/en-IN/index.js
  src/locale/en-IN/index.js.flow
  src/locale/en-IN/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1774 danish month abbrevations should end with period
  src/locale/da/_lib/localize/index.js
  src/locale/da/_lib/match/index.js
  src/locale/da/snapshot.md
  src/locale/nl/_lib/match/index.js
Labels: ⛴ Ship it!, 🌏 I18n

#1775 Add a missing preposition to the Spanish locale.
  src/locale/es/_lib/formatLong/index.js
  src/locale/es/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n

#1776 Add eachHourOfInterval function (#1764)
  src/eachHourOfInterval/benchmark.js
  src/eachHourOfInterval/index.d.ts
  src/eachHourOfInterval/index.js
  src/eachHourOfInterval/index.js.flow
  src/eachHourOfInterval/test.js
  src/fp/eachHourOfInterval/index.d.ts
  src/fp/eachHourOfInterval/index.js
  src/fp/eachHourOfInterval/index.js.flow
  src/fp/eachHourOfIntervalWithOptions/index.d.ts
  src/fp/eachHourOfIntervalWithOptions/index.js
  src/fp/eachHourOfIntervalWithOptions/index.js.flow
  src/fp/index.js
  src/fp/index.js.flow
  src/index.js
  src/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🎉 Feature

#1777 improve it formatRelative (gender + this/last/nextWeek handling)
  src/locale/it/_lib/formatRelative/index.js
  src/locale/it/snapshot.md
Labels: ⛴ Ship it!, 🌏 I18n
