Repository date-fns/date-fns, pull requests merged in 2021-09, with the labels that each got.

#2594 convert `sub` to TypeScript
  src/sub/index.ts
  src/sub/test.ts
Labels: TypeScript migration

#2584 added ar-TN locale
  src/locale/ar-TN/_lib/formatDistance/index.ts
  src/locale/ar-TN/_lib/formatLong/index.ts
  src/locale/ar-TN/_lib/formatRelative/index.ts
  src/locale/ar-TN/_lib/localize/index.ts
  src/locale/ar-TN/_lib/match/index.ts
  src/locale/ar-TN/index.ts
  src/locale/ar-TN/snapshot.md
  src/locale/index.js
Labels: 🌏 I18n

#2574 modified grammar in the CHANGELOG.md file
  CHANGELOG.md
Labels: 📃 Docs

#2571 converting -0 to 0 when it appears
  src/_lib/roundingMethods/index.ts
  src/differenceInHours/index.ts
  src/differenceInHours/test.ts
  src/differenceInMilliseconds/index.ts
  src/differenceInMilliseconds/test.ts
  src/differenceInMinutes/index.ts
  src/differenceInMinutes/test.js
  src/differenceInMinutes/test.ts
  src/differenceInMonths/index.ts
  src/differenceInMonths/test.ts
  src/differenceInQuarters/index.ts
  src/differenceInQuarters/test.ts
  src/differenceInSeconds/index.ts
  src/differenceInSeconds/test.ts
  src/differenceInWeeks/index.ts
  src/differenceInWeeks/test.ts
  src/types.ts
Labels: 🌟 Improvement
