Repository date-fns/date-fns, pull requests merged in 2021-12, with the labels that each got.

#2811 added uz-Cyrl locale
  src/locale/uz-Cyrl/_lib/formatDistance/index.js
  src/locale/uz-Cyrl/_lib/formatLong/index.js
  src/locale/uz-Cyrl/_lib/formatRelative/index.js
  src/locale/uz-Cyrl/_lib/localize/index.js
  src/locale/uz-Cyrl/_lib/match/index.js
  src/locale/uz-Cyrl/index.js
  src/locale/uz-Cyrl/snapshot.md
Labels: 🌏 I18n

#2183 Add West Frisian (fy) support
  src/locale/fy/_lib/formatDistance/index.js
  src/locale/fy/_lib/formatLong/index.js
  src/locale/fy/_lib/formatRelative/index.js
  src/locale/fy/_lib/localize/index.js
  src/locale/fy/_lib/match/index.js
  src/locale/fy/index.d.ts
  src/locale/fy/index.js
  src/locale/fy/index.js.flow
  src/locale/fy/snapshot.md
  typings.d.ts
Labels: 🌏 I18n

#2679 migrate formatters to TS
  src/_lib/format/formatters/index.ts
  src/locale/types.ts
  src/types.ts
Labels: Hacktoberfest, TypeScript migration, hacktoberfest-accepted

#2813 migrate parseISO to TypeScript
  src/parseISO/index.ts
  src/parseISO/test.ts
  src/types.ts
Labels: TypeScript migration

#2835 Feat(docs)/update examples
  src/isSameDay/index.ts
  src/isSameHour/index.ts
  src/isSameISOWeek/index.ts
  src/isSameMinute/index.ts
  src/isSameMonth/index.ts
  src/isSameQuarter/index.ts
  src/isSameSecond/index.ts
  src/isSameWeek/index.ts
Labels: 📃 Docs

#2822 docs: remove an extra digit
  src/isMatch/index.ts
  src/lightFormat/index.ts
  src/parse/index.js
Labels: 📃 Docs

#2814 `parse` fix: allow `K` token to be used with `a` or `b`
  src/parse/_lib/parsers/index.js
  src/parse/test.js
Labels: 🐜 Bug fix

#2669 Migrate hi locale
  src/locale/hi/_lib/formatDistance/index.js
  src/locale/hi/_lib/formatDistance/index.ts
  src/locale/hi/_lib/formatLong/index.ts
  src/locale/hi/_lib/formatRelative/index.js
  src/locale/hi/_lib/formatRelative/index.ts
  src/locale/hi/_lib/localize/index.ts
  src/locale/hi/_lib/match/index.ts
  src/locale/hi/index.ts
  src/locale/types.ts
Labels: Hacktoberfest, TypeScript migration, hacktoberfest-accepted

#2845 fix `hi` locale type issues
  src/locale/hi/_lib/formatDistance/index.ts
  src/locale/hi/_lib/formatRelative/index.ts
  src/locale/hi/_lib/localize/index.ts
  src/locale/hi/_lib/match/index.ts
  src/locale/hi/index.ts
  src/locale/types.ts
Labels: 🌏 I18n, TypeScript

#2315 Migrate formatRFC7231 function
  src/formatRFC7231/index.ts
  src/formatRFC7231/test.ts
Labels: TypeScript migration

#2313 Migrate formatISO9075 function
  src/formatISO9075/index.ts
  src/formatISO9075/test.ts
Labels: TypeScript migration

#2850 `it` locale TS migration
  src/locale/en-US/_lib/match/index.ts
  src/locale/it/_lib/formatDistance/index.js
  src/locale/it/_lib/formatDistance/index.ts
  src/locale/it/_lib/formatLong/index.ts
  src/locale/it/_lib/formatRelative/index.ts
  src/locale/it/_lib/localize/index.ts
  src/locale/it/_lib/match/index.ts
  src/locale/it/index.ts
  src/locale/types.ts
Labels: 🌏 I18n, TypeScript migration

#2854 `is` locale TS migration
  src/locale/is/_lib/formatDistance/index.js
  src/locale/is/_lib/formatDistance/index.ts
  src/locale/is/_lib/formatLong/index.ts
  src/locale/is/_lib/formatRelative/index.js
  src/locale/is/_lib/formatRelative/index.ts
  src/locale/is/_lib/localize/index.ts
  src/locale/is/_lib/match/index.ts
  src/locale/is/index.ts
  src/locale/is/snapshot.md
Labels: 🌏 I18n, TypeScript migration

#2856 `id` locale TS migration
  src/locale/id/_lib/formatDistance/index.js
  src/locale/id/_lib/formatDistance/index.ts
  src/locale/id/_lib/formatLong/index.ts
  src/locale/id/_lib/formatRelative/index.js
  src/locale/id/_lib/formatRelative/index.ts
  src/locale/id/_lib/localize/index.ts
  src/locale/id/_lib/match/index.ts
  src/locale/id/index.ts
Labels: 🌏 I18n, TypeScript migration

#2857 `ja-Hira` locale ts migration
  src/locale/ja-Hira/_lib/formatDistance/index.js
  src/locale/ja-Hira/_lib/formatDistance/index.ts
  src/locale/ja-Hira/_lib/formatLong/index.ts
  src/locale/ja-Hira/_lib/formatRelative/index.js
  src/locale/ja-Hira/_lib/formatRelative/index.ts
  src/locale/ja-Hira/_lib/localize/index.ts
  src/locale/ja-Hira/_lib/match/index.ts
  src/locale/ja-Hira/index.ts
Labels: 🌏 I18n, TypeScript migration

#2858 `ko` locale TS migration
  src/locale/ko/_lib/formatDistance/index.js
  src/locale/ko/_lib/formatDistance/index.ts
  src/locale/ko/_lib/formatLong/index.ts
  src/locale/ko/_lib/formatRelative/index.js
  src/locale/ko/_lib/formatRelative/index.ts
  src/locale/ko/_lib/localize/index.ts
  src/locale/ko/_lib/match/index.ts
  src/locale/ko/index.ts
Labels: 🌏 I18n, TypeScript migration

#2859 `sk` locale TS migration
  src/locale/sk/_lib/formatDistance/index.js
  src/locale/sk/_lib/formatDistance/index.ts
  src/locale/sk/_lib/formatLong/index.ts
  src/locale/sk/_lib/formatRelative/index.ts
  src/locale/sk/_lib/localize/index.ts
  src/locale/sk/_lib/match/index.ts
  src/locale/sk/index.ts
Labels: 🌏 I18n, ✋ Help wanted, TypeScript migration

#2598 convert `getWeekOfMonth` to TypeScript
  src/getWeekOfMonth/index.ts
  src/getWeekOfMonth/test.ts
Labels: TypeScript migration

#2872 upgrade browserslist / caniuse-lite dep
  yarn.lock
Labels: ⚙️ Chore, dependencies

#2861 improvements to CONTRIBUTING.md docs
  CONTRIBUTING.md
Labels: 📃 Docs, ⛴ Ship it!

#2879 Sync number of functions that date-fns offers
  docs/gettingStarted.md
Labels: 📃 Docs, ⛴ Ship it!

#2881 `bn` locale TypeScript conversion
  src/locale/bn/_lib/formatDistance/index.js
  src/locale/bn/_lib/formatDistance/index.ts
  src/locale/bn/_lib/formatLong/index.ts
  src/locale/bn/_lib/formatRelative/index.js
  src/locale/bn/_lib/formatRelative/index.ts
  src/locale/bn/_lib/localize/index.ts
  src/locale/bn/_lib/match/index.ts
  src/locale/bn/index.ts
Labels: 🌏 I18n, ⛴ Ship it!, TypeScript migration

#2882 `bs` locale TypeScript conversion
  src/locale/bs/_lib/formatDistance/index.ts
  src/locale/bs/_lib/formatLong/index.ts
  src/locale/bs/_lib/formatRelative/index.ts
  src/locale/bs/_lib/localize/index.ts
  src/locale/bs/_lib/match/index.ts
  src/locale/bs/index.ts
  src/locale/bs/snapshot.md
Labels: 🌏 I18n, ⛴ Ship it!, TypeScript migration

#2869 fix short abbreviation for Spanish locale
  src/locale/es/_lib/localize/index.ts
  src/locale/es/_lib/match/index.ts
Labels: 🌏 I18n, ⛴ Ship it!
