Repository date-fns/date-fns, pull requests merged in 2021-02, with the labels that each got.

#2180 Doc changes
  CONTRIBUTING.md
  docs/gettingStarted.md
Labels: 📃 Docs

#2099 A week should start on Sunday in Japanese locale
  src/locale/ja/index.js
Labels: 🌏 I18n, 🐜 Bug fix

#2185 Fix differenceInMonths
  src/differenceInMonths/index.js
  src/differenceInMonths/test.js
Labels: 🐜 Bug fix

#1624 Update examples provided for toDate, once a replacement for parse
  src/parse/index.js
Labels: 📃 Docs

#2010 fix suffixes for kk language
  src/locale/kk/_lib/localize/index.js
  src/locale/kk/snapshot.md
Labels: hacktoberfest-accepted, ⛴ Ship it!, 🌏 I18n

#2016 Use aaa and bbb for lowercase am/pm
  src/_lib/format/formatters/index.js
  src/_lib/format/lightFormatters/index.js
  src/format/index.js
  src/format/test.js
  src/lightFormat/test.js
  src/locale/az/snapshot.md
  src/locale/be/snapshot.md
  src/locale/ca/snapshot.md
  src/locale/da/snapshot.md
  src/locale/en-AU/snapshot.md
  src/locale/en-CA/snapshot.md
  src/locale/en-GB/snapshot.md
  src/locale/en-IN/snapshot.md
  src/locale/en-NZ/snapshot.md
  src/locale/en-US/snapshot.md
  src/locale/es/snapshot.md
  src/locale/et/snapshot.md
  src/locale/eu/snapshot.md
  src/locale/fr-CA/snapshot.md
  src/locale/fr-CH/snapshot.md
  src/locale/fr/snapshot.md
  src/locale/gd/snapshot.md
  src/locale/gl/snapshot.md
  src/locale/gu/snapshot.md
  src/locale/hr/snapshot.md
  src/locale/hy/snapshot.md
  src/locale/id/snapshot.md
  src/locale/it/snapshot.md
  src/locale/ka/snapshot.md
  src/locale/kk/snapshot.md
  src/locale/ms/snapshot.md
  src/locale/mt/snapshot.md
  src/locale/nl-BE/snapshot.md
  src/locale/nl/snapshot.md
  src/locale/pl/snapshot.md
  src/locale/pt-BR/snapshot.md
  src/locale/pt/snapshot.md
  src/locale/ro/snapshot.md
  src/locale/ru/snapshot.md
  src/locale/sk/snapshot.md
  src/locale/sr-Latn/snapshot.md
  src/locale/sr/snapshot.md
  src/locale/tr/snapshot.md
  src/locale/uk/snapshot.md
  src/locale/uz/snapshot.md
  src/locale/vi/snapshot.md
Labels: hacktoberfest-accepted, ⛴ Ship it!, 🌏 I18n

#2117 Update formatRFC3339 documentation
  src/formatRFC3339/index.js
Labels: 📃 Docs

#2104 docs: Support TypeScript in REPL example
  CONTRIBUTING.md
Labels: 📃 Docs

#2080 Basque (eu) lange correction
  src/locale/eu/_lib/formatLong/index.js
Labels: 🌏 I18n

#2111 Fix czech short and medium date formats
  src/locale/cs/_lib/formatLong/index.js
Labels: 🌏 I18n

#2145 Migrate to date-fns.org v3
  jsdoc2md.json
  package.json
  scripts/_lib/firebase.js
  scripts/release/updateFirebase.js
  yarn.lock
Labels: ⚙️ Chore

#2187 Adjusting [pl] translations of formatDistance
  src/locale/pl/_lib/formatDistance/index.js
  src/locale/pl/snapshot.md
Labels: 🌏 I18n

#2170 Fix typo locale for pt-BR
  src/locale/pt-BR/_lib/localize/index.js
Labels: 🌏 I18n

#2172 Add intlFormat function
  .babelrc.js
  package.json
  src/intlFormat/index.ts
  src/intlFormat/test.ts
  yarn.lock
Labels: 🎉 Feature

#2053 Migrate setDayOfYear to TS
  src/setDayOfYear/index.ts
  src/setDayOfYear/test.ts
Labels: TypeScript migration, hacktoberfest-accepted

#2230 move isMonday to ts
  src/isMonday/index.ts
  src/isMonday/test.ts
Labels: TypeScript migration

#2229 move isLeapYear to ts
  src/isLeapYear/index.ts
  src/isLeapYear/test.ts
Labels: TypeScript migration

#2228 move isLastDayOfMonth to ts
  src/isLastDayOfMonth/index.ts
  src/isLastDayOfMonth/test.ts
Labels: TypeScript migration

#2227 move isFuture to ts
  src/isFuture/index.ts
  src/isFuture/test.ts
Labels: TypeScript migration

#2226 move isFriday to ts
  src/isFriday/index.ts
  src/isFriday/test.ts
Labels: TypeScript migration

#2225 move isExists to ts
  src/isExists/index.ts
  src/isExists/test.ts
Labels: TypeScript migration
