Repository date-fns/date-fns, pull requests merged in 2021-07, with the labels that each got.

#2541 Add example to formatRelative
  src/formatRelative/index.ts
Labels: 📃 Docs

#2533 Update software license format to enable Github detection
  LICENSE.md
Labels: 📃 Docs

#2520 fix: extra punctuation in DE medium date
  src/locale/de-AT/snapshot.md
  src/locale/de/_lib/formatLong/index.ts
  src/locale/de/snapshot.md
Labels: 🌏 I18n

#2495 Add Bosnian locale
  src/locale/bs/_lib/formatDistance/index.js
  src/locale/bs/_lib/formatLong/index.js
  src/locale/bs/_lib/formatRelative/index.js
  src/locale/bs/_lib/localize/index.js
  src/locale/bs/_lib/match/index.js
  src/locale/bs/index.d.ts
  src/locale/bs/index.js
  src/locale/bs/index.js.flow
  src/locale/bs/snapshot.md
  src/locale/index.js
  src/locale/index.js.flow
  typings.d.ts
Labels: ⛴ Ship it!, 🌏 I18n

#2471 Add some more ordinal formatting for Japanese values
  src/locale/ja/_lib/localize/index.js
  src/locale/ja/_lib/match/index.js
  src/locale/ja/snapshot.md
Labels: 🌏 I18n

#2498 Add clamp function
  src/clamp/index.ts
  src/clamp/test.ts
  src/index.js
Labels: 🎉 Feature

#2535 Adjust Flemish short date format
  src/locale/nl-BE/_lib/formatLong/index.js
  src/locale/nl-BE/snapshot.md
Labels: 🌏 I18n
