Repository date-fns/date-fns, pull requests merged in 2021-03, with the labels that each got.

#2259 Fix documentation not being generated for intlFormat (closes #2258)
  src/intlFormat/index.ts
Labels: ⚙️ Chore, 🐜 Bug fix, 📃 Docs

#2269 Fix getTimezoneOffsetInMilliseconds to fix the tests failing after Chrome upgrade
  src/_lib/getTimezoneOffsetInMilliseconds/index.js
  src/addDays/test.ts
  src/differenceInCalendarDays/test.js
  src/differenceInDays/test.js
  src/format/test.js
  src/lightFormat/test.js
  src/parse/test.js
  src/parseISO/index.js
  src/parseISO/test.js
Labels: ⛴ Ship it!

#2057 Migrate `is*ISOWeek` functions
  src/isSameISOWeek/index.ts
  src/isSameISOWeek/test.ts
  src/isSameISOWeekYear/index.ts
  src/isSameISOWeekYear/test.ts
  src/isThisISOWeek/index.ts
  src/isThisISOWeek/test.ts
Labels: TypeScript migration, hacktoberfest-accepted

#2291 Add nextWednesday, nextThursday, nextFriday, nextSaturday, nextSunday
  src/nextFriday/index.ts
  src/nextFriday/test.ts
  src/nextMonday/index.ts
  src/nextSaturday/index.ts
  src/nextSaturday/test.ts
  src/nextSunday/index.ts
  src/nextSunday/test.ts
  src/nextThursday/index.ts
  src/nextThursday/test.ts
  src/nextTuesday/index.ts
  src/nextWednesday/index.ts
  src/nextWednesday/test.ts
Labels: 🎉 Feature

#2329 Fix formatDistanceStrict DST-related bug (fixes #2307)
  scripts/test/dst.sh
  src/formatDistanceStrict/index.js
  test/dst/formatDistanceStrict/cairo.ts
  test/dst/formatDistanceStrict/melbourne.ts
Labels: ⛴ Ship it!, 🐜 Bug fix

#2331 Fix formatDuration function example
  src/formatDuration/index.js
Labels: 📃 Docs

#2285 Migrate setQuarter function
  src/setQuarter/index.ts
  src/setQuarter/test.ts
Labels: TypeScript migration

#2286 Migrate setSeconds function
  src/setSeconds/index.ts
  src/setSeconds/test.ts
Labels: TypeScript migration

#2282 Migrate setMilliseconds function
  src/setMilliseconds/index.ts
  src/setMilliseconds/test.ts
Labels: TypeScript migration

#2281 Migrate setISOWeekYear function
  src/setISOWeekYear/index.ts
  src/setISOWeekYear/test.ts
Labels: TypeScript migration

#2280 Migrate setISOWeek function
  src/setISOWeek/index.ts
  src/setISOWeek/test.ts
Labels: TypeScript migration

#2284 Migrate setMonth function
  src/setMonth/index.ts
  src/setMonth/test.ts
Labels: TypeScript migration

#2288 Migrate setYear function
  src/setYear/index.ts
  src/setYear/test.ts
Labels: TypeScript migration

#1961 Added Mongolian language support
  src/locale/mn/_lib/formatDistance/index.js
  src/locale/mn/_lib/formatLong/index.js
  src/locale/mn/_lib/formatRelative/index.js
  src/locale/mn/_lib/localize/index.js
  src/locale/mn/_lib/match/index.js
  src/locale/mn/index.d.ts
  src/locale/mn/index.js
  src/locale/mn/index.js.flow
  src/locale/mn/snapshot.md
Labels: 🌏 I18n

#2279 Migrate setISODay function
  src/setISODay/index.ts
  src/setISODay/test.ts
Labels: TypeScript migration

#2276 Migrate setDate function
  src/setDate/index.ts
  src/setDate/test.ts
Labels: TypeScript migration

#2328 Fix typos in JSDoc example section of milliseconds
  src/milliseconds/index.ts
Labels: 📃 Docs

#2326 Fix typo in summary of milliseconds function
  src/milliseconds/index.ts
Labels: 📃 Docs

#2301 Fix typo in comment of eachHourOfInterval function
  src/eachHourOfInterval/index.ts
Labels: 📃 Docs

#2360 Translate min function to TS
  src/min/index.ts
  src/min/test.js
  src/min/test.ts
Labels: TypeScript migration
