Repository date-fns/date-fns, pull requests merged in 2021-11, with the labels that each got.

#2734 Convert nextX and previousX functions to v3
  src/nextDay/index.ts
  src/nextDay/test.ts
  src/nextFriday/index.ts
  src/nextMonday/index.ts
  src/nextMonday/test.ts
  src/nextSaturday/index.ts
  src/nextSunday/index.ts
  src/nextThursday/index.ts
  src/nextTuesday/index.ts
  src/nextTuesday/test.ts
  src/nextWednesday/index.ts
  src/previousDay/index.ts
  src/previousDay/test.ts
  src/previousFriday/index.ts
  src/previousFriday/test.ts
  src/previousMonday/index.ts
  src/previousMonday/test.ts
  src/previousSaturday/index.ts
  src/previousSaturday/test.ts
  src/previousSunday/index.ts
  src/previousSunday/test.ts
  src/previousThursday/index.ts
  src/previousThursday/test.ts
  src/previousTuesday/index.ts
  src/previousTuesday/test.ts
  src/previousWednesday/index.ts
  src/previousWednesday/test.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#2732 Convert isThisX functions to v3
  src/isThisHour/index.ts
  src/isThisHour/test.ts
  src/isThisISOWeek/index.ts
  src/isThisISOWeek/test.ts
  src/isThisMinute/index.ts
  src/isThisMinute/test.ts
  src/isThisMonth/index.ts
  src/isThisMonth/test.ts
  src/isThisQuarter/index.ts
  src/isThisQuarter/test.ts
  src/isThisSecond/index.ts
  src/isThisSecond/test.ts
  src/isThisWeek/index.ts
  src/isThisWeek/test.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#2652 Update Locale docs where its properties are used
  docs/Locale.js
Labels: Hacktoberfest, hacktoberfest-accepted

#2658 Fix/change abbreviation locale id follow momentjs
  src/locale/id/_lib/localize/index.js
Labels: Hacktoberfest, hacktoberfest-accepted

#1633 update era translations
  src/locale/az/_lib/match/index.js
Labels: 🌏 I18n

#2675 migrate addLeadingZeros to TS
  src/_lib/addLeadingZeros/index.js
  src/_lib/addLeadingZeros/index.ts
  src/_lib/addLeadingZeros/test.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#2729 locale hi - fix october translation
  src/locale/hi/_lib/localize/index.js
Labels: 🌏 I18n, Hacktoberfest, hacktoberfest-accepted

#1968 Migration: 'closestTo' functions to TS
  src/closestIndexTo/index.ts
  src/closestIndexTo/test.js
  src/closestIndexTo/test.ts
  src/closestTo/index.ts
  src/closestTo/test.js
  src/closestTo/test.ts
Labels: TypeScript

#2722 Fix path when deleting the esm version of outdated locales during build
  scripts/build/removeOutdatedLocales.js
Labels: Hacktoberfest, hacktoberfest-accepted

#2699 feat: add locale ar-EG
  src/locale/ar-EG/_lib/formatDistance/index.ts
  src/locale/ar-EG/_lib/formatLong/index.ts
  src/locale/ar-EG/_lib/formatRelative/index.ts
  src/locale/ar-EG/_lib/localize/index.ts
  src/locale/ar-EG/_lib/match/index.ts
  src/locale/ar-EG/index.d.ts
  src/locale/ar-EG/index.js.flow
  src/locale/ar-EG/index.ts
  src/locale/ar-EG/index.ts.flow
  src/locale/ar-EG/snapshot.md
Labels: 🌏 I18n, Hacktoberfest, hacktoberfest-accepted

#2686 add zh-HK locale
  src/locale/index.js
  src/locale/index.js.flow
  src/locale/zh-HK/_lib/formatDistance/index.js
  src/locale/zh-HK/_lib/formatLong/index.js
  src/locale/zh-HK/_lib/formatRelative/index.js
  src/locale/zh-HK/_lib/localize/index.js
  src/locale/zh-HK/_lib/match/index.js
  src/locale/zh-HK/index.d.ts
  src/locale/zh-HK/index.js
  src/locale/zh-HK/index.js.flow
  src/locale/zh-HK/snapshot.md
  typings.d.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#2721 Add Arabic locale
  outdatedLocales.json
  src/locale/ar/_lib/formatDistance/index.js
  src/locale/ar/_lib/formatDistance/index.ts
  src/locale/ar/_lib/formatLong/index.js
  src/locale/ar/_lib/formatLong/index.ts
  src/locale/ar/_lib/formatRelative/index.js
  src/locale/ar/_lib/formatRelative/index.ts
  src/locale/ar/_lib/localize/index.js
  src/locale/ar/_lib/localize/index.ts
  src/locale/ar/_lib/match/index.js
  src/locale/ar/_lib/match/index.ts
  src/locale/ar/index.js
  src/locale/ar/index.ts
  src/locale/ar/index.ts.flow
  src/locale/ar/snapshot.md
  src/locale/index.js
Labels: 🌏 I18n, Hacktoberfest, hacktoberfest-accepted

#2772 Add En-IE locale 🇮🇪 ☘️
  src/locale/en-IE/index.ts
  src/locale/en-IE/snapshot.md
Labels: 🌏 I18n

#2683 Update getWeek documentation to reference the correct function
  src/getWeek/index.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#2730 docs: fix grammar in i18nContributionGuide.md
  docs/i18nContributionGuide.md
Labels: 📃 Docs, Hacktoberfest, hacktoberfest-accepted

#2678 migrate longFormatters to TS
  src/_lib/format/longFormatters/index.ts
Labels: Hacktoberfest, TypeScript migration, hacktoberfest-accepted

#2095 migrate formatDuration to TS
  src/formatDuration/index.ts
  src/formatDuration/test.ts
Labels: TypeScript migration

#2701 Increase test code coverage for addBusinessDays
  src/addBusinessDays/test.ts
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2691 Increase test code coverage for _lib/format/formatters/*
  src/_lib/format/formatters/index.js
  src/format/test.js
  src/lightFormat/test.ts
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2703 Increase test code coverage for formatISO API
  src/formatISO/test.js
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2705 Increase test code coverage for formatRFC3339
  src/formatRFC3339/test.ts
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2706 Increase test code coverage for getWeekOfMonth
  src/getWeekOfMonth/test.js
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2708 Increase test code coverage for intervalToDuration
  src/intervalToDuration/test.ts
Labels: 🌟 Improvement, Hacktoberfest, hacktoberfest-accepted

#2786 100% code coverage for formatDuration API
  src/formatDuration/test.ts
Labels: 🌟 Improvement

#2603 Fix eachMinuteOfInterval interval validation
  src/eachMinuteOfInterval/index.ts
  src/eachMinuteOfInterval/test.ts
Labels: 🐜 Bug fix

#2720 Migrate tr locale
  src/locale/tr/_lib/formatDistance/index.js
  src/locale/tr/_lib/formatDistance/index.ts
  src/locale/tr/_lib/formatLong/index.ts
  src/locale/tr/_lib/formatRelative/index.js
  src/locale/tr/_lib/formatRelative/index.ts
  src/locale/tr/_lib/localize/index.ts
  src/locale/tr/_lib/match/index.ts
  src/locale/tr/index.ts
  src/locale/tr/snapshot.md
Labels: 🌏 I18n, Hacktoberfest, hacktoberfest-accepted

#2713 Add Khmer(km) Locale Support
  src/locale/_lib/buildLocalizeFn/index.ts
  src/locale/km/_lib/formatDistance/index.ts
  src/locale/km/_lib/formatLong/index.ts
  src/locale/km/_lib/formatRelative/index.ts
  src/locale/km/_lib/localize/index.ts
  src/locale/km/_lib/match/index.ts
  src/locale/km/index.d.ts
  src/locale/km/index.js.flow
  src/locale/km/index.ts
  src/locale/km/index.ts.flow
  src/locale/km/snapshot.md
  src/locale/types.ts
Labels: 🌏 I18n, Hacktoberfest, hacktoberfest-accepted

#2680 migrate getUTCWeekYear to TS
  src/_lib/getUTCISOWeekYear/index.ts
  src/_lib/getUTCISOWeekYear/test.js
  src/_lib/getUTCISOWeekYear/test.ts
  src/_lib/getUTCWeekYear/index.ts
  src/_lib/getUTCWeekYear/test.js
  src/_lib/getUTCWeekYear/test.ts
Labels: Hacktoberfest, TypeScript migration, hacktoberfest-accepted

#2677 migrate startOfUTCWeek to TS
  src/_lib/startOfUTCWeek/index.ts
  src/_lib/startOfUTCWeek/test.js
  src/_lib/startOfUTCWeek/test.ts
  src/_lib/startOfUTCWeekYear/index.ts
  src/_lib/startOfUTCWeekYear/test.js
  src/_lib/startOfUTCWeekYear/test.ts
Labels: Hacktoberfest, TypeScript migration, hacktoberfest-accepted

#2579 Fix the format of zeros in formatDuration in Czech locale
  src/locale/cs/_lib/formatDistance/index.js
  src/locale/cs/snapshot.md
Labels: 🌎 I18n fix

#2038 Fix Estonian date patterns
  src/locale/et/_lib/formatLong/index.js
  src/locale/et/_lib/match/index.js
  src/locale/et/snapshot.md
Labels: hacktoberfest-accepted, 🌎 I18n fix

#2797 [i18n]: replace LT -> p, L -> P in ar, fil, ka locales
  src/locale/fil/_lib/formatRelative/index.js
  src/locale/ka/_lib/formatRelative/index.js
  src/locale/ka/snapshot.md
Labels: 🌎 I18n fix

#1632 correct some words translations
  src/locale/az/_lib/localize/index.js
Labels: 🌏 I18n

#2213 Fix short date separator for Romanian locale
  src/locale/ro/_lib/formatLong/index.js
Labels: 🌎 I18n fix

#2771 fix(locale): fix zhCN quarter translation
  src/locale/zh-CN/_lib/localize/index.js
Labels: 🌎 I18n fix
