Repository date-fns/date-fns, pull requests merged in 2021-04, with the labels that each got.

#2380 Update Contribution Guide
  CONTRIBUTING.md
Labels: 📃 Docs

#2382 added function - eachMinuteOfInterval
  src/eachMinuteOfInterval/benchmark.js
  src/eachMinuteOfInterval/index.ts
  src/eachMinuteOfInterval/test.ts
Labels: 🎉 Feature

#2361 Remove extra leading 0
  src/format/index.js
Labels: ⛴ Ship it!

#2355 Migrate isSaturday function
  src/isSaturday/index.ts
  src/isSaturday/test.ts
Labels: TypeScript migration

#2347 Migrate isToday function
  src/isToday/index.ts
  src/isToday/test.ts
Labels: TypeScript migration

#2349 Migrate isTuesday function
  src/isTuesday/index.ts
  src/isTuesday/test.ts
Labels: TypeScript migration

#2393 migrate getWeeksInMonth to ts
  src/getWeeksInMonth/index.ts
  src/getWeeksInMonth/test.ts
Labels: TypeScript migration

#2394 migrate isWithinInterval to ts
  src/isWithinInterval/index.ts
  src/isWithinInterval/test.ts
Labels: TypeScript migration
