Repository date-fns/date-fns, pull requests merged in 2022-06, with the labels that each got.

#2173 Intl format relative
  src/constants/index.ts
  src/intlFormatDistance/index.ts
  src/intlFormatDistance/test.ts
  src/types.ts
  tsconfig.json
Labels: 🚧 WIP

#2974 Missing dot for abbreviated Saturday in IS locale
  src/locale/is/_lib/localize/index.ts
Labels: 🌎 I18n fix

#3045 Fix weekday matcher in `tr` locale
  src/locale/tr/_lib/match/index.ts
  src/locale/tr/snapshot.md
Labels: 🌎 I18n fix

#2941 Fixed constants TS typings
  scripts/build/_lib/typings/typeScript.js
  src/constants/index.d.ts
  typings.d.ts
Labels: TypeScript, 🐜 Bug fix
