Repository date-fns/date-fns, pull requests merged in 2022-07, with the labels that each got.

#3062 Update Locale docs description to include a sorted list of fns
  docs/Locale.js
Labels: 📃 Docs

#3078 fixed error in jsdocs of diffrenceInBuisnessDays
  src/differenceInBusinessDays/index.ts
Labels: 📃 Docs

#3059 Fix CS locale parsing
  src/locale/cs/_lib/match/index.ts
Labels: 🌎 I18n fix

#2924 formatDistance: fixes suffix for AZ
  src/locale/az/_lib/formatDistance/index.ts
  src/locale/az/snapshot.md
Labels: 🌎 I18n fix

#3091 Added support for ceil and floor in roundToNearestMinutes
  src/locale/is/_lib/localize/index.ts
  src/roundToNearestMinutes/index.ts
  src/roundToNearestMinutes/test.ts
  src/types.ts
Labels: 🎉 Feature

#3115 Added Belarusian Classic (Tarask) language support
  src/locale/be-TAR/_lib/formatDistance/index.ts
  src/locale/be-TAR/_lib/formatLong/index.ts
  src/locale/be-TAR/_lib/formatRelative/index.ts
  src/locale/be-TAR/_lib/localize/index.ts
  src/locale/be-TAR/_lib/match/index.ts
  src/locale/be-TAR/index.js.flow
  src/locale/be-TAR/index.ts
  src/locale/be-TAR/snapshot.md
Labels: 🌏 I18n

#3125 Add `@name` in constants jsdocs to fix type generation duplication
  src/constants/index.d.ts
  src/constants/index.ts
  src/fp/index.js.flow
  src/index.js.flow
  typings.d.ts
Labels: Flow, TypeScript, 🐜 Bug fix
