Repository date-fns/date-fns, pull requests merged in 2022-01, with the labels that each got.

#2427 Add comment on FirstWeekContainsDate type
  src/types.ts
Labels: ⛴ Ship it!

#2058 Migrate eachWeekendOfYear to TS
  src/eachDayOfInterval/index.ts
  src/eachDayOfInterval/test.ts
  src/eachWeekendOfYear/index.ts
  src/eachWeekendOfYear/test.ts
Labels: TypeScript migration, hacktoberfest-accepted

#2880 build script: FP and Indices conversion to TypeScript
  scripts/_lib/listFPFns.js
  scripts/_lib/listFns.js
  scripts/_lib/listLocales.js
  scripts/build/build.sh
  scripts/build/fp.js
  scripts/build/fp.ts
  scripts/build/indices.js
  scripts/build/indices.ts
Labels: 🌟 Improvement, TypeScript migration

#2895 migrate `ru` locale
  src/locale/ru/_lib/formatDistance/index.ts
  src/locale/ru/_lib/localize/index.ts
  src/locale/ru/_lib/match/index.ts
Labels: ⛴ Ship it!, TypeScript migration

#2093 Migrate formatDistanceToNowStrict to TS
  src/formatDistanceToNowStrict/index.ts
  src/formatDistanceToNowStrict/test.ts
Labels: ⛴ Ship it!, TypeScript migration

#2883 `uk` locale TS migration
  src/locale/uk/_lib/formatDistance/index.ts
  src/locale/uk/_lib/formatLong/index.ts
  src/locale/uk/_lib/formatRelative/index.js
  src/locale/uk/_lib/formatRelative/index.ts
  src/locale/uk/_lib/localize/index.ts
  src/locale/uk/_lib/match/index.ts
  src/locale/uk/index.ts
Labels: ⛴ Ship it!

#1617 Change ordinalNumber formatting in IT locale
  src/locale/it/_lib/localize/index.ts
  src/locale/it/snapshot.md
Labels: 🌎 I18n fix

#2092 migrate formatDistanceToNow to TS
  src/formatDistanceToNow/index.ts
  src/formatDistanceToNow/test.ts
Labels: TypeScript migration

#2106 new locale: Occitan (closes #2061)
  src/locale/oc/_lib/formatDistance/index.ts
  src/locale/oc/_lib/formatLong/index.ts
  src/locale/oc/_lib/formatRelative/index.ts
  src/locale/oc/_lib/localize/index.ts
  src/locale/oc/_lib/match/index.ts
  src/locale/oc/index.ts
  src/locale/oc/snapshot.md
Labels: 🎉 Feature, 🌏 I18n

#2086 Migrate format to TS
  src/_lib/format/formatters/index.ts
  src/format/index.ts
  src/format/test.ts
  src/formatDistance/index.ts
  src/formatDistanceToNow/test.ts
  src/formatDuration/index.ts
  src/formatRelative/index.ts
  src/locale/types.ts
Labels: TypeScript migration

#2912 More TS-ification chores
  scripts/release/buildChangelog.ts
  src/_lib/assign/index.js
  src/_lib/assign/index.ts
  src/_lib/cloneObject/index.js
  src/_lib/cloneObject/index.ts
  src/_lib/getTimezoneOffsetInMilliseconds/index.ts
  src/_lib/protectedTokens/index.ts
  src/eachQuarterOfInterval/index.ts
  src/eachWeekOfInterval/index.ts
  src/endOfYear/index.ts
  src/format/index.ts
  src/formatDistance/index.ts
  src/formatDistanceStrict/index.ts
  src/formatDistanceStrict/test.ts
  src/locale/gd/_lib/localize/index.ts
  src/locale/ka/_lib/localize/index.ts
  src/locale/nn/_lib/formatDistance/index.ts
  src/locale/sv/_lib/formatDistance/index.ts
  src/locale/types.ts
Labels: ⚙️ Chore

#2886 added it-CH locale
  src/locale/it-CH/_lib/formatLong/index.ts
  src/locale/it-CH/index.d.ts
  src/locale/it-CH/index.js.flow
  src/locale/it-CH/index.ts
  src/locale/it-CH/snapshot.md
Labels: 🌏 I18n
