Repository date-fns/date-fns, pull requests merged in 2024-06, with the labels that each got.

#3740 fix: fix dateFormats.short of the bg locale
  src/locale/bg/_lib/formatLong/index.ts
  src/locale/bg/snapshot.md
Labels: 🌏 I18n, 🌎 I18n fix

#3832 chore: Fix typos in documentation
  src/constants/index.ts
  src/constructFrom/index.ts
  src/differenceInBusinessDays/index.ts
  src/formatISO/index.ts
  src/isMatch/index.ts
  src/isValid/index.ts
  src/milliseconds/index.ts
  src/millisecondsToSeconds/index.ts
  src/parse/index.ts
  src/subBusinessDays/index.ts
Labels: 📃 Docs

#3813 Fix typos
  CHANGELOG.md
  scripts/build/fp.ts
  src/addBusinessDays/test.ts
  src/constants/index.ts
  src/eachMinuteOfInterval/test.ts
  src/format/test.ts
  src/fp/_lib/convertToFP/test.ts
  src/getOverlappingDaysInIntervals/test.ts
  src/isMatch/index.ts
  src/lightFormat/test.ts
  src/locale/_lib/buildMatchFn/index.ts
  src/locale/_lib/buildMatchPatternFn/index.ts
  src/locale/types.ts
  src/parse/index.ts
  src/parse/test.ts
  src/parseJSON/test.ts
  src/roundToNearestHours/test.ts
  src/setDefaultOptions/index.ts
  src/startOfToday/test.ts
  src/subBusinessDays/test.ts
  test/dst/tzOffsetTransitions.ts
Labels: 📃 Docs, ⚙️ Chore
