Repository date-fns/date-fns, pull requests merged in 2024-01, with the labels that each got.

#3448 Fix plural form of weeks in Swedish
  src/locale/sv/_lib/formatDistance/index.ts
  src/locale/sv/snapshot.md
Labels: 🌏 I18n

#3540 Add yearsToDays Function
  src/yearsToDays/index.ts
  src/yearsToDays/test.ts
Labels: 🎉 Feature

#3677 fix `getUnixTime` import path (and the browser tests)
  src/getUnixTime/index.ts
Labels: 🔥 Important, 🐜 Bug fix
